### ISSUE TITLE
PDFType1Font bug

### ISSUE THREAD

**Issue by naivefeeling** [pdfminer/pdfminer.six#288] opened 2019-08-26 04:28 UTC
In pdffont.py
```python
        try:
            (descriptor, widths) = FontMetricsDB.get_metrics(self.basefont)
        except KeyError:
            descriptor = dict_value(spec.get('FontDescriptor', {}))
```
> Note: For the standard 14 fonts, the entries FirstChar, LastChar, Widths, and FontDescriptor must either all be present or all be absent. Ordinarily, they are absent; specifying them enables a standard font to be overridden (see “Standard Type 1 Fonts (Standard 14 Fonts),” below). -pdf_reference1.7.pdf

**Comment by pietermarsman** [comment] 2019-08-26 15:50
Could you explain in more detail what the bug is?

**Comment by jstockwin** [comment] 2020-07-09 14:34
@naivefeeling Just a quick bump as we're currently working through all the open issues. Are you able to provide more details on this?

**Comment by pietermarsman** [comment] 2020-07-18 14:16
Closing this because not reproducible.

**Closed by pietermarsman** 2020-07-18 14:16 UTC
Labels: type: bug
