### ISSUE TITLE
log.debug statements in psparser.py slow things down a lot

### ISSUE THREAD

**Issue by jeffoneill** [pdfminer/pdfminer.six#347] opened 2019-12-30 15:10 UTC
I was doing a little debugging of a PDF that pdfminer.six processes slowly, and the culprit was `psparser.py`.  

Turns out that if you delete all the `log.debug` statements, processing is sped up by nearly 25%.  On one PDF, processing time was reduced from 52 seconds to 40 seconds.

Any objections to doing this?

**Comment by pietermarsman** [comment] 2019-12-30 17:20
That seems like a lot of time to spend on debugging messages. I sometimes use them, but I can imagine that most people don't. 

Would you mind generating some statistics with `timeit` on this? Preferably with pdfs from the `samples/` directory. 

I'm not sure what we could do about this. Obviously removing them is one thing, but maybe there is an alternative that is both functional and fast. We are probably not the first to experience this.

**Comment by jeffoneill** [comment] 2019-12-30 18:38
There is already a debug (-d) flag.  We could just wrap the log.debug statements in an `if` statement that is true only if the debug flag is set.  That is actually what the parent project of this one does.

By the way, now that both the original pdfminer and pdfminer.six are Python 3 only does it make sense to combine efforts?

**Comment by pietermarsman** [comment] 2019-12-30 19:15
> Would you mind generating some statistics with `timeit` on this? Preferably with pdfs from the `samples/` directory.

I've done some testing and I cannot replicate what you describe. 

```python
from timeit import timeit

from pdfminer.high_level import extract_text


def test():
    extract_text('samples/nonfree/dmca.pdf')


print(timeit(test, number=10))
```

With debug statements: 100.51 seconds
Without debugging statements (i've replaced all `log.debug(.*)` statements with pass): 99.54 seconds

**Comment by pietermarsman** [comment] 2019-12-30 19:17
> By the way, now that both the original pdfminer and pdfminer.six are Python 3 only does it make sense to combine efforts?

Yes, we are both on Python3 now. Last time somebody checked @euske was not interested in collaborating on https://github.com/euske/pdfminer.

**Comment by pietermarsman** [comment] 2019-12-30 19:18
What Python are you using?

**Comment by jeffoneill** [comment] 2019-12-30 19:20
> I've done some testing and I cannot replicate what you describe.

The `psparser` module is only used for PDFs that contain embedded postscript (ps stands for postscript) and most PDFs don't have this.  I can't share the file I'm working with, but I'll try to find another PDF with postscript.

I'm testing with Python 3.6.9.  I don't expect that to matter.

**Comment by pietermarsman** [comment] 2020-01-06 21:09
I think the `psparser` is also used to parse PDF documents, since PDF is an extention of PS. I just debugged through some of the functions of `psparser` for another PR. 

Also, when I run the script in my earlier https://github.com/pdfminer/pdfminer.six/issues/347#issuecomment-569768663, and output logging statements to the console (e.g. using `logging.basicConfig(level=logging.DEBUG)`); I get a lot of debug messages starting with `DEBUG:pdfminer.psparser`. 

I was asking about your Python version, because my `log.debug()` implementation is:

```python
if self.isEnabledFor(DEBUG):
    self._log(DEBUG, msg, args, **kwargs)
```

The `self.isEnabledFor(DEBUG)` is very cheap, and all the string formatting is postponed to when the log statement actually needs to be printed (see [docs](https://docs.python.org/3.7/howto/logging.html#optimization)). Perhaps you have a different implementation of `log.debug`?

Did you test while printing debugging statements to the console? Printing takes a lot of time, so you should compare [with `log.debug()`] to [without `log.debug()`] without printing in both scenarios. 

Sorry if I ask some silly questions, but I cannot replicate this issue and that makes it super hard to fix it.

**Comment by fakabbir** [comment] 2020-03-03 11:23
I tried using pdfminer inside a flask app with debug on, Interestingly it starts printing the debug message `DEBUG:pdfminer.psparser` even without mentioning it in pdfminer. The process was slow too.

```
# Run Flask app
if __name__ == '__main__':
    setup.check_director()
    web_app.secret = "text-extraction"
    web_app.run(host='0.0.0.0', port=8084, debug=True, threaded=True)
```

```
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
pdfminer.six            20200124
```
@pietermarsman  Do you see this important to work on  decreasing speed, while logging ?

**Comment by pietermarsman** [comment] 2020-03-03 20:33
I am not exactly sure what your question is. 

I'm willing to work on this issue but I'm having troubles to replicate it and that makes it very difficult to solve it. 

It's OK for pdfminer to be slower if debugging messages are on.

**Comment by fakabbir** [comment] 2020-03-05 05:35
In case the messages are too much and slowing it down, it could be turned off using `logging.getLogger("pdfminer").setLevel(logging.WARNING)`.

_Do you see this important to work on decreasing speed, while logging ?_

I meant that if the slow speed is only due to logging and no internals withing psparser is involved we can close this issue. In case you feel that there is some scope of improvement then we may mark it for work.

**Comment by pietermarsman** [comment] 2020-03-07 18:45
> In case the messages are too much and slowing it down, it could be turned off using `logging.getLogger("pdfminer").setLevel(logging.WARNING)`.

That's what I think, but the way I read this issue is that pdfminer is slow because of the `log.debug` statement when the logging level is `logging.INFO` or higher. 

> _Do you see this important to work on decreasing speed, while logging ?_
> 
> I meant that if the slow speed is only due to logging and no internals withing psparser is involved we can close this issue. In case you feel that there is some scope of improvement then we may mark it for work.

I don't think it is important. During debugging speed is not important. 

I'm closing this issue since I can not reproduce it and the python docs state that having `log.debug` statements are cheap.

**Closed by pietermarsman** 2020-03-07 18:45 UTC
Labels: type:performance

**Comment by vdmitriyev** [comment] 2020-11-10 13:52
I had the similar issue while using Flask + pdfminer + logger. 

After multiple runs the log file was filled with debug log from pdfminer and I was not able to disable debug level logging by using:
```python
from pdfminer.high_level import extract_text
...
output_txt = extract_text(fin, debug=False)
```
I also check ```tools/pdf2txt.py``` from [here](https://github.com/pdfminer/pdfminer.six/blob/ef4787d8add35c84ed324e488a0683485b422f45/tools/pdf2txt.py) and it looks like this parameter never passed to the ```extract_text()``` or not interpreted by the ```extract_text()``` correctly.

The solution provided by @fakabbir solved the issue in my case. After switching loglevel type directly in the code as suggested, I had no debugging information in logs from pdfminer anymore.
