### ISSUE TITLE
'è' added if using an stream different from io.StringIO

### ISSUE THREAD

**Issue by ZanonEdoardo** [pdfminer/pdfminer.six#191] opened 2018-10-10 12:20 UTC
'è' was added in head of stream if using an stream different from `io.StringIO` in 
```class PDFConverter(PDFLayoutAnalyzer).__init__```

https://github.com/pdfminer/pdfminer.six/blob/master/pdfminer/converter.py#L173

Is this neccesary? Is possible check the stream in another method?

Code for test the problem: 

```
    from pdfminer.converter import TextConverter
    from pdfminer.layout import LAParams
    from pdfminer.pdfinterp import PDFResourceManager

    def testBuffer(self):
        rsrcmgr = PDFResourceManager()
        buffer = cStringIO.StringIO()
        retstr = codecs.getwriter("utf-8")(buffer)
        laparams = LAParams(detect_vertical=True, char_margin=3.0, line_margin=0.8, all_texts=True,
                            word_margin=0.6, line_overlap=0.3)
        device = TextConverter(rsrcmgr, retstr, codec="utf-8", laparams=laparams)
        print(buffer)
```

**Comment by pietermarsman** [comment] 2020-01-22 21:51
It is currently here:

https://github.com/pdfminer/pdfminer.six/blob/bc494ff03cc2d1139a7806a8ca74a477a67f14e9/pdfminer/converter.py#L169

It looks like a test to check if unicode characters can be written to the stream. If not, the output is written as bytes instead of unicode. 

How can we test if a stream accepts unicode without actually writing a unicode value?

**Comment by pietermarsman** [comment] 2020-05-21 17:00
Hi @ZanonEdoardo! I tried testing this but it's hard to come up with a stream that does not have a mode (i.e. file handlers) or is StringIO or BytesIO. The cStringIO.StringIO does not exist anymore in Python 3. Do you know what other stream someone wants to use? 

As a solution to this problem I wanted to write a backslash character to the stream. I guess that works fine, but I cannot test it since all of the streams I know do not end up in the `else` clause where this code is executed.

**Comment by jstockwin** [comment] 2020-07-09 14:52
@pietermarsman I notice you moved this to in progress. Are you currently working on this? Any updated to your above comment, or are we really waiting for info/a solution?

**Comment by pietermarsman** [comment] 2020-07-11 10:01
It's more of a "needs solution".

The core of this issue is that we need to have a way to determine if the output stream supports unicode. If it is not any of the output streams we know, you can test this by printing a unicode character. That character appears on the output stream. This can be fixed by printing a backspace. This works when you print the output to a terminal or so, but it might be worse if you want to use the output for other cases. Because there are 2 characters in the output stream that are not in the original PDF. So I'm not sure if that is always an improvement. 

Also, I think using python3 mitigates this problem almost completely. Since all the default python streams support unicode. So we can maybe remove the test (because it never triggers).

Anyway, if we want to continue with this issue, we need an example of an output stream that does not support unicode and has a valid usecase.

**Comment by pietermarsman** [comment] 2020-10-18 11:59
I would suggest we remove the try-except way of figuring out if the stream is binary. The check for the mode of the stream shoudl not actually write to the stream. If this leads to unexpected behavior for stream implementations, of which I do not yet know the existence, we can add specific checks for those.

**Closed** 2020-10-25 13:37 UTC
Labels: type: bug
