### ISSUE TITLE
Pages End Tag Not Exists When Xml Export 

### ISSUE THREAD

**Issue by ramcorreio** [pdfminer/pdfminer.six#459] opened 2020-07-20 01:21 UTC
**Bug report**

- Pages End Tag Not Exists When Xml Export

A few steps to check. See below:
- read the pdf usgin "open" function native python
- export xml to file using XMLConverter and boxes_flow = 0 and word_margin = 0 in LAParams
- now read the XML generated in the previous step
- using parse in xml.dom.minidom and will see the follow error

```
Traceback (most recent call last):
  File "xml-conv.py", line 106, in <module>
    to_dom (f)
  File "xml-conv.py", line 92, in to_dom
    xml = minidom.parse (filePath)
  File "C: \ Users \ ramco \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ xml \ dom \ minidom.py", line 1958, in parse
    return expatbuilder.parse (file)
  File "C: \ Users \ ramco \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ xml \ dom \ expatbuilder.py", line 911, in parse
    result = builder.parseFile (fp)
  File "C: \ Users \ ramco \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ xml \ dom \ expatbuilder.py", line 211, in parseFile
    parser.Parse ("", True)
xml.parsers.expat.ExpatError: no element found: line 3183, column 0
```

**Comment by pietermarsman** [comment] 2020-07-20 19:10
Hi @ramcorreio, after carefull reading of your bug report I assume you're asking the following: 

- You are trying to convert a pdf to xml using pdfminer.six
- The resulting xml is not valid according to the python builtin xml parser

Is this correct? That would suprise me because the `</pages>` is written when the `XMLConverter` is closed (see this line). 

Could you share the PDF you are using? Can you also share the exact code / command you are using to generate the xml?

**Comment by pietermarsman** [comment] 2020-10-18 10:40
Closing because not reproducible (no example pdf).

**Closed by pietermarsman** 2020-10-18 10:40 UTC
Labels: type: bug
