### ISSUE TITLE
How to custom newline  (LAparams) when converting to XML?

### ISSUE THREAD

**Issue by dersuchendee** [pdfminer/pdfminer.six#417] opened 2020-04-13 10:25 UTC
I have this document: https://drive.google.com/file/d/18Kmq4kD2Xai7w9KAROIJZ-6baCKjHA5H/view?usp=sharing

And I converted it in XML with PDFminer. Problem is, I want to have a custom newline every time there are those longer whitspaces, for instance, in the first line, I want to have a newline before the "1" because there is a longer space:

Titolo Il Causidico] sps. a Don Rodrigo [ BIG SPACE ] 1 sventura]sps. a mi-

I tried setting custom LAparams out, but I don't know how to achieve this. My code so far is:

```
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import HTMLConverter,TextConverter,XMLConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
import io

def convert(case, pdfpath, targetfilepath, pages=100):
    if not pages: pagenums = set();
    else:         pagenums = set(pages);
    manager = PDFResourceManager()
    codec = 'utf-8'
    caching = True
    word_margin = 1
    laparams2 = LAParams(all_texts=True, detect_vertical=True,
                      line_overlap=0.5, char_margin=1000.0, #set char_margin to a large number
                      line_margin=0.5, word_margin=0.5,
                      boxes_flow=0.5)

    if case == 'text':
        output = io.StringIO()
        converter = TextConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'HTML':
        output = io.BytesIO()
        converter = HTMLConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'XML':
        output = io.BytesIO()
        converter = XMLConverter(manager, output, codec=codec, laparams= laparams2)

    interpreter = PDFPageInterpreter(manager, converter)
    infile = open(pdfpath, 'rb')

    for page in PDFPage.get_pages(infile, pagenums,caching=caching, check_extractable=True):
        interpreter.process_page(page)

    convertedPDF = output.getvalue()

    infile.close(); converter.close(); output.close()

    convertedFile = open(targetfilepath, 'wb')
    convertedFile.write(convertedPDF)
    convertedFile.close()

print(convert('XML', 'fel_split2.pdf', 'fe2.xml', pages=None))
```

**Comment by pietermarsman** [comment] 2020-05-09 13:21
Hi! You can try setting boxes-flow to `None`. This disables the box layout algorithm, and does not merge lines into paragraphs. The order can be counter-intuitive but it will put both sides of the big space on a separate line.

**Comment by dersuchendee** [comment] 2020-05-11 15:26
Hey, thank you very much for your answer! Unfortunately it doesn't work, I really wish there was a guide to set LAParams :(

**Comment by pietermarsman** [comment] 2020-05-16 14:18
This might give some insight: https://pdfminersix.readthedocs.io/en/latest/topics/converting_pdf_to_text.html

But I agree that there can be much better guides on this.

**Comment by jstockwin** [comment] 2020-06-23 15:10
@dersuchendee I think you're really close. Actually you don't need to change your `word_margin`. What is happening is that the lines in each block are very close together, and so are being merged into a single text box, with explicit new lines at the end of each line.

To have a new line after the big gap, we want each bit to be it's own text box. We therefore want to stop each block from being a single text box. If you reduce the line margin (e.g. to 0.1) then this should work. @pietermarsman Is right that you also don't need `boxes_flow` here.

So, if you replace your LAParams with the following I think it should work as expected:

```
    laparams2 = LAParams(
        all_texts=True,
        detect_vertical=True,
        line_overlap=0.5,
        char_margin=2.0,
        line_margin=0.1,
        word_margin=0.5,
        boxes_flow=None,
    )
```

**Comment by pietermarsman** [comment] 2020-06-29 18:50
@dersuchendee does that work for you? 

(I am closing this as I think this question is answered by @jstockwin)

**Comment by dersuchendee** [comment] 2020-06-30 08:14
Honestly, it doesn't work... it messes up words and boxes flow = None gives error, replacing it with 0 works but there are still some issues.

**Comment by dersuchendee** [comment] 2020-06-30 08:15
> @dersuchendee does that work for you?
> 
> (I am closing this as I think this question is answered by @jstockwin)

Honestly, it doesn't work... it messes up words and boxes flow = None gives error, replacing it with 0 works but there are still some issues.

**Comment by jstockwin** [comment] 2020-06-30 08:31
@dersuchendee what version are you using? `boxes_flow=None` is new so you might need to update. It's different from `boxes_flow=0`.

IIRC on old versions you can get the same behaviour by passing boxes_flow outside the -1 - 1 range, e.g. `boxes_flow=2`.

If you're up you date but it's still giving an error, what's the error?

If there are still issues after using `None` (or 2), what are they?

**Comment by dersuchendee** [comment] 2020-06-30 08:40
@jstockwin Just to be sure, is this correct?

`from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import HTMLConverter,TextConverter,XMLConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage`

or do I have to put .six or 3?

**Comment by jstockwin** [comment] 2020-06-30 08:47
That's correct. You need to use `pdfminer.six` for pip install etc, but when importing it's just `pdfminer`.

**Comment by dersuchendee** [comment] 2020-06-30 09:11
Okay, done! After the upgrade it converts no text.

Code:

`from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import HTMLConverter,TextConverter,XMLConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
import io
import lxml.etree as etree
import re
from xml.dom import minidom
from xml.etree import ElementTree as ET
import pandas as pd
from bs4 import BeautifulSoup


def convert(case, pdfpath, targetfilepath, pages=100):
    if not pages: pagenums = set();
    else:         pagenums = set(pages);
    manager = PDFResourceManager()
    codec = 'utf-8'
    caching = True
    laparams = LAParams(all_texts=True)
    laparams.boxes_flow = -0.5
    # laparams.paragraph_indent = 0.2
    laparams.detect_vertical = True
    # laparams.heuristic_word_margin = 0.03
    laparams.line_overlap = 0.2
    laparams.word_margin = 0.2
    laparams.line_margin = 0.5
    laparams.char_margin = 1000.0




    if case == 'text':
        output = io.StringIO()
        converter = TextConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'HTML':
        output = io.BytesIO()
        converter = HTMLConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'XML':
        output = io.BytesIO()
        converter = XMLConverter(manager, output, codec=codec, laparams= laparams)

    interpreter = PDFPageInterpreter(manager, converter)
    infile = open(pdfpath, 'rb')

    for page in PDFPage.get_pages(infile, pagenums,caching=caching, check_extractable=True):
        interpreter.process_page(page)

    convertedPDF = output.getvalue()

    infile.close(); converter.close(); output.close()

    convertedFile = open(targetfilepath, 'wb')
    convertedFile.write(convertedPDF)
    convertedFile.close()

    return targetfilepath`

**Comment by jstockwin** [comment] 2020-06-30 10:11
@dersuchendee That code has a few changes from your original one, and I still don't understand your LA Params (you still don't have boxes flow disabled, you still have a large line margin and a massive char margin). Please try with the ones I said?

If you run your original code snippet from your first post on this issue, but change the LAParams to `laparams2 = LAParams(all_texts=True, line_margin=0.1, boxes_flow=None)` then it should work okay. At least for me I get a reasonable looking XML file saved: https://www.dropbox.com/s/pdqp9htdbrz4xzp/fe2.xml?dl=0

**Comment by dersuchendee** [comment] 2020-06-30 10:29
@jstockwin I tried with yours, but it still won't work :/ I don't understand

**Comment by jstockwin** [comment] 2020-06-30 10:43
Hm, then me neither. Is the output on my dropbox link what you're looking for?

What is the error? Or just the output is different for you?

You said there was an error during installation, what was that error?

I am using `pdfminer.six==20200517` and this is my code:

```
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import HTMLConverter, TextConverter, XMLConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
import io


def convert(case, pdfpath, targetfilepath, pages=100):
    if not pages:
        pagenums = set()
    else:
        pagenums = set(pages)
    manager = PDFResourceManager()
    codec = "utf-8"
    caching = True
    laparams2 = LAParams(all_texts=True, line_margin=0.1, boxes_flow=None)

    if case == "text":
        output = io.StringIO()
        converter = TextConverter(manager, output, codec=codec, laparams=LAParams())
    if case == "HTML":
        output = io.BytesIO()
        converter = HTMLConverter(manager, output, codec=codec, laparams=LAParams())
    if case == "XML":
        output = io.BytesIO()
        converter = XMLConverter(manager, output, codec=codec, laparams=laparams2)

    interpreter = PDFPageInterpreter(manager, converter)
    infile = open(pdfpath, "rb")

    for page in PDFPage.get_pages(
        infile, pagenums, caching=caching, check_extractable=True
    ):
        interpreter.process_page(page)

    convertedPDF = output.getvalue()

    infile.close()
    converter.close()
    output.close()

    convertedFile = open(targetfilepath, "wb")
    convertedFile.write(convertedPDF)
    convertedFile.close()


convert("XML", "fel_split2.pdf", "fe2.xml", pages=None)
```

**Comment by dersuchendee** [comment] 2020-06-30 11:08
I have the same version as you, and the error is: `ERROR: pdfplumber 0.5.16 has requirement pdfminer.six==20200104, but you'll have pdfminer-six 20200517 which is incompatible.`

**Comment by jstockwin** [comment] 2020-06-30 11:09
I don't think that error should matter, since it's about another package...

What happens when you run the code?

**Comment by dersuchendee** [comment] 2020-06-30 11:12
Your code works, but when I use it in my pipeline it returns nothing at all, while it did before!

I don't understand, because the xml output should be the same anyway.

Full code:

```
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import HTMLConverter,TextConverter,XMLConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
import io
import lxml.etree as etree
import re
from xml.dom import minidom
from xml.etree import ElementTree as ET
import pandas as pd

def convert(case, pdfpath, targetfilepath, pages=100):
    if not pages: pagenums = set();
    else:         pagenums = set(pages);
    manager = PDFResourceManager()
    codec = 'utf-8'
    caching = True
    word_margin = 1
    laparams2 = LAParams(all_texts=True, detect_vertical=True,
                      line_overlap=0.5, char_margin=1000.0, #set char_margin to a large number
                      line_margin=0.5, word_margin=0.5,
                      boxes_flow=0.5)

    laparams3 = LAParams(all_texts=True, line_margin=0.1, boxes_flow=None)

    if case == 'text':
        output = io.StringIO()
        converter = TextConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'HTML':
        output = io.BytesIO()
        converter = HTMLConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'XML':
        output = io.BytesIO()
        converter = XMLConverter(manager, output, codec=codec, laparams= laparams3)

    interpreter = PDFPageInterpreter(manager, converter)
    infile = open(pdfpath, 'rb')

    for page in PDFPage.get_pages(infile, pagenums,caching=caching, check_extractable=True):
        interpreter.process_page(page)

    convertedPDF = output.getvalue()

    infile.close(); converter.close(); output.close()

    convertedFile = open(targetfilepath, 'wb')
    convertedFile.write(convertedPDF)
    convertedFile.close()

    return targetfilepath

def uniform_cm(pdfpath):
    targetfilepath = convert('XML', pdfpath, 'bo.xml', pages=None)
    parser = etree.XMLParser(remove_blank_text=True, recover=True)
    ntree = etree.parse(targetfilepath, parser)


    for node in ntree.getiterator():
        if node.attrib.get('size') == '10.439':
            node.attrib['size'] = '10.238'
    root = ntree.getroot()
    for node in ntree.getiterator():
        if node.attrib.get('size') == '10.060'  or node.attrib.get('size') =='10.958':
            node.attrib['size'] = '10.482'
    root = ntree.getroot()

    for node in ntree.getiterator():
        if node.attrib.get('size') == '8.988' or node.attrib.get('size') =='6.926' :
            node.attrib['size'] = '10.238'
    root = ntree.getroot()
    #print(ET.tostring(root))
    return ntree

def getBBoxFirstValue(line):
    if line is not None:
        bb = line.attrib.get('bbox')
        if bb is not None:
            try:
                return float(bb.split(",")[0])
            except ValueError:
                pass
    return None

# Remove all 'textline' elements
def due(pdfpath):
    ntree = uniform_cm(pdfpath)
    etree.strip_tags(ntree, 'textline')

    # Search for all text "textbox" elements
    for textbox in ntree.xpath('//textbox'):
        new_line = etree.Element("new_line")
        previous_bb = None

        # From a given textbox element, iterate over all the "text" elements
        for x in textbox.iter("text"):
            # Get current bb valu
            bb = getBBoxFirstValue(x)
            # Check current and past values aren't empty
            if bb is not None and previous_bb is not None and (bb - previous_bb) > 20:
                # Inserte newline into parent tag
                x.getparent().insert(x.getparent().index(x), new_line)

                # A new "new_line" element is created
                new_line = etree.Element("new_line")

            # Append current element is new_line tag
            new_line.append(x)

            # Keep latest non empty BBox 1st value
            if bb is not None:
                previous_bb = bb

        # Add last new_line element if not null
        textbox.append(new_line)
    tree = ntree
    return tree

def newline(pdfpath):
    tree = due(pdfpath)
    root = tree.getroot()
    for new_line_block in tree.xpath('//new_line'):
        # Find all "text" element in the new_line block
        list_text_elts = new_line_block.findall('text')

        # Iterate over all of them with the current and previous ones
        for previous_text, current_text in zip(list_text_elts[:-1], list_text_elts[1:]):
            # Get size elements
            prev_size = previous_text.attrib.get('size')
            curr_size = current_text.attrib.get('size')
            # If they are equals and not both null
            if curr_size == prev_size and curr_size is not None:
                # Get current and previous text
                pt = previous_text.text if previous_text.text is not None else ""
                ct = current_text.text if current_text.text is not None else ""
                # Add them to current element
                current_text.text = pt + ct
                # Remove preivous element
                previous_text.getparent().remove(previous_text)

    newtree = etree.tostring(root, encoding='utf-8', pretty_print=True)
    # newtree = newtree.decode("utf-8")
    return newtree

def get_xml_by_tag_names(xml_path, tag_name_1, tag_name_2):

    data = {}
    xml_tree = minidom.parseString(xml_path)
    item_group_nodes = xml_tree.getElementsByTagName(tag_name_1)
    for idx, item_group_node in enumerate(item_group_nodes):
        cl_compile_nodes = item_group_node.getElementsByTagName(tag_name_2)
        for _ in cl_compile_nodes:
            data[idx]=[item_group_node.toxml()]
    return data


def find_regex_fasi(regex, text):
    matches_fasi = re.findall(regex, text)
    return len(matches_fasi)

def find_regex(regex, text, opzione2= None, opzione3 = None, opzione4 = None, opzione5=None):
    lista = []
    for x in text:
        matches_prima = re.findall(regex, x)
        matches_prima2 = []
        matches_prima3 = []
        matches_prima4 = []
        matches_prima5 = []
        if opzione2 is not None:
            matches_prima2 = re.findall(opzione2, x)
            if opzione3 is not None:
                matches_prima3 = re.findall(opzione3, x)
                if opzione4 is not None:
                    matches_prima4 = re.findall(opzione4, x)
                    if opzione5 is not None:
                        matches_prima5 = re.findall(opzione5, x)
        lunghezza = len(matches_prima) + len(matches_prima2) + len(matches_prima3) + len(matches_prima4) + len(matches_prima5)
        lista.append(lunghezza)
        #print(matches_prima, matches_prima2, matches_prima3, matches_prima4, matches_prima5)
    return sum(lista)



def search_delete_append(dizionario, dizionariofasi):
    deletekeys = []

    for k in dizionario:
        for v in dizionario[k]:
            if "7.489" in v:
                deletekeys.append(k)
                dizionariofasi[k] = v

    for item in deletekeys:
        del dizionario[item]

def clean(dizionario, lista):
    for value in dizionario.values():
        myxml = ' '.join(value)
        tree = ET.fromstring(myxml)
        tmpstring = ' '.join(text.text for text in tree.findall('text'))
        for to_remove in ("<", ">", ".", ",", ";", "-", "!", ":", "’", "?", "<>", "=", "|", "(", ")", "\n", "/", "\uf8ee", "−", "[]","↔", "…" ):
            tmpstring = tmpstring.replace(to_remove, "")
        lista.append(tmpstring)
    return lista

def clean_fasi(dizionario, lista):
    pattern = re.compile("(?<!\d)\d{2}(?!\d)")
    for value in dizionario.values():

        myxml2 = ''.join(value)
        tree2 = ET.fromstring(myxml2)
        tmpstring2 = ' '.join(text.text for text in tree2.findall('text'))
        for to_remove in ("<", ">", ".", ",", ";", "-", "!", ":", "’", "?", "<>", "=", "|", "(", ")", "\n", "/", "\uf8ee", "−", "[]","↔", "…"):
            tmpstring2 = tmpstring2.replace(to_remove, "")
            tmpstring2 = pattern.sub("", tmpstring2)
        lista.append(tmpstring2)
    return lista

def main(pdfpath):
    newtree= newline(pdfpath)
    dict_fasi = {}
    data = get_xml_by_tag_names(newtree, 'new_line', 'text')
    search_delete_append(data, dict_fasi)
    testoo = []
    clean(data, testoo)
    #testo = ''.join(testo)
    find_prima = re.compile(r"\]\s*prima(?!\S)")

    
    #################

    testo_fasi = []
    values = [x for x in dict_fasi.values()]
    myxml_fasi = ' '.join(values)
    find_CM = re.compile(r"10\.238")
    find_regex_fasi(find_CM, myxml_fasi) #quanti CM ci sono?
    #print(myxml_fasi)
    clean_fasi(dict_fasi, testo_fasi)
    #testo_fasi = ''.join(testo_fasi)
    print(testo_fasi)


    

print(main('fet1c1.pdf'))

```

**Comment by jstockwin** [comment] 2020-06-30 11:24
Again, you still have the wrong layout parameters in your code, please try the ones I sent.

If I fix that, your code writes a file called `be.xml` which has the correct contents.

Perhaps the issue is that you need to read the file somewhere, but it since the written output is correct I'm not sure this is a bug with `pdfminer.six`?

**Comment by dersuchendee** [comment] 2020-06-30 11:30
Even with your parameters, it won't work. The code works with version `20200104`, I might as well keep on working with that at this point! I don't know what could be the difference

**Comment by jstockwin** [comment] 2020-06-30 11:37
Hm, I'm not sure. I'm afraid I don't have the time to look through your code at the moment. You said at some point that my code worked, so perhaps start there and build up until you find the issue? Given it writes the correct xml file, I think it must be something after that. Sorry I can't help further

**Comment by pietermarsman** [comment] 2020-07-05 11:03
**On the original problem**

> Problem is, I want to have a custom newline every time there are those longer whitspaces, for instance, in the first line, I want to have a newline before the "1" because there is a longer space:

Try the code sample below. The `char_margin` makes sure that the longer whitespaces split into two lines. The `line_margin` makes sure that those two lines never get merged into a box.

```
from pdfminer.high_level import extract_text
from pdfminer.layout import LAParams

text = extract_text('/home/pieter/Downloads/fel_split2.pdf',
                    laparams=LAParams(char_margin=2.0, line_margin=0.0))
print(text)
```

The output is: 

```
PPARATO

24a

Titolo Il Causidico] sps. a Don Rodrigo

1 sventura] sps. a mi-

seria

della quale non conosce che una parte;] prima 1che non

conosce ancora appieno;

2che
```

@dersuchendee make sure that you post a minimal reproducible example. Using these large code fragments makes it difficult to pinpoint what's going wrong.

**Closed by pietermarsman** 2020-07-05 11:03 UTC
Labels: type: documentation, type: question
