### ISSUE TITLE
dumppdf.py unable to extract ToC

### ISSUE THREAD

**Issue by ortenburger** [pdfminer/pdfminer.six#180] opened 2018-08-20 19:30 UTC
File "./dumppdf.py", line 143, in dumpoutline
    pageno = pages[dest[0].objid]
AttributeError: 'int' object has no attribute 'objid'

Will inspect this issue further, as soon as i got some time on my hands

**Comment by winlp4ever** [comment] 2019-06-10 20:16
Please, I have encountered the same error, has anyone try to fix this issue already?

**Comment by VagosGrigoropoulos** [comment] 2019-08-03 20:18
Same here

**Comment by pietermarsman** [comment] 2019-09-10 06:55
@ortenburger, thanks for raising the issue. This is a very late response. Do you have any possibility to find the pdf that caused the issue?

**Comment by pietermarsman** [comment] 2020-01-22 21:32
@ortenburger @winlp4ever @VagosGrigoropoulos can you post a pdf that we can use to replicate this issue?

**Comment by pietermarsman** [comment] 2020-05-21 16:15
Closing this because not reproducible.

**Closed by pietermarsman** 2020-05-21 16:15 UTC
Labels: type: bug

**Comment by HartBlanc** [comment] 2020-06-29 21:05
I have no idea if this will help anyone else, but I was able to resolve the problem by deleting a random page of the document in Preview (MacOS) (both the last page and a random page in the middle worked). 

I did some very basic debugging, the value of `dest` passed to `resolve_dest` was a bytes object (b'merged-report.toc'), which doesn't seem to match any of the cases.

Unfortunately, I cannot share the example pdf as a reproducible example because I don't have permission to share the file.

Happy to help in whatever way I can without sharing docouments.

**Comment by tycho** [comment] 2020-07-04 08:54
I can reproduce this issue with the current version of the ARMv8-a reference manual PDF:

https://developer.arm.com/documentation/ddi0487/latest/arm-architecture-reference-manual-armv8-for-armv8-a-architecture-profile

**Comment by pietermarsman** [comment] 2020-07-05 12:15
@tycho can you create a new issue for this? Make sure to also include the code/commands that you use.

**Comment by tycho** [comment] 2020-07-05 16:15
@pietermarsman It's an identical issue to the OP though, why make a new issue? Basically just `dumppdf.py --extract-toc $pdffile` with the PDF from the link I provided above.

**Comment by pietermarsman** [comment] 2020-07-07 18:46
This issue was closed because it is not reproducible. If you create a new issue you should include the command you use, and the pdf you are testing on (unlike this issue).
