### ISSUE TITLE
not working with PDF version 1.3

### ISSUE THREAD

**Issue by NitinSafaya** [pdfminer/pdfminer.six#387] opened 2020-03-11 08:40 UTC
I am trying to extract text from few pdf docs. pdfminer.six is able to parse text from pdf v1.4-1.7 but it is not working for pdf v1.3. Most of the time it is returning text from starting from the 3rd page instead of page 1.

**Comment by pietermarsman** [comment] 2020-03-14 09:30
Hi @NitinSafaya, thanks for raising the issue! Could you attach an example PDF + code that you are using. This helps us debugging and fixing the issue.

**Comment by NitinSafaya** [comment] 2020-03-16 14:18
```
    for lt_object in lt_objects:
        if isinstance(lt_object, LTTextBox) is False:
            continue
        for inner_obj in lt_object:
            if isinstance(inner_obj, LTTextLineHorizontal) is False:
                continue
            text = inner_obj.get_text()

Unfortunately, I can not share the PDF v1.3 file due to client's restrictions

**Comment by pietermarsman** [comment] 2020-03-16 19:24
Hi @NitinSafaya, without the pdf there is not much we can do. For that reason I'm closing this. If you ever find another PDF with version 1.3, feel free to reopen. 

PDF 1.3 is a subset of PDF 1.7 so I expect most things to work and perhaps the problem is not due to the version of the PDF but other things. You could try using `mutools` to clean/repair the pdf and then view the PDF again. 

Are you getting any errors? Is the text you want to extract selectable when you view it? Can you copy it to a text editor?

**Closed by pietermarsman** 2020-03-16 19:24 UTC
