### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp36-win_amd64.pyd': Failed to load dynlib/dll 

### ISSUE THREAD

**Issue by aaonline** [pdfminer/pdfminer.six#195] opened 2018-10-18 03:55 UTC
I am writing a basic engine to parse PDF files, and use pdfminer as:

from pdfminer.pdfpage import PDFPage

But when I try building an exe using PyInstaller 3.3.1 on Windows 10 (Home), inside a virtualenv in Anaconda, I get following error:-

```
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': 
Trying '_raw_ecb.cp36-win_amd64.pyd': Failed to load dynlib/dll 'C:\Users\User\AppData\Local\Temp\_MEI222122\Crypto\Util\..\Cipher\_raw_ecb.cp36-win_amd64.pyd'. Most probably this dynlib/dll was not found when the application was frozen., 
Trying '_raw_ecb.pyd': Failed to load dynlib/dll 'C:\Users\User\AppData\Local\Temp\_MEI222122\Crypto\Util\..\Cipher\_raw_ecb.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[18920] Failed to execute script
```

And if I do not include the import above, exe is built success.

I went to the site packages and it looks like

site-packages\pycryptodome-3.6.3-py3.6-win-amd64.egg\Crypto\Util

Please any suggestions here.

**Comment by ohaiyofei** [comment] 2019-09-11 01:42
Hi,

I also encounter this error on jupyter, have anyone solve it?

**Comment by pietermarsman** [comment] 2020-01-22 21:41
I think this is a duplicate of #143. That issue is closed because it is an issue with pyinstaller and pycryptodome and has nothing to do with pdfminer. Also see https://github.com/pyinstaller/pyinstaller/issues/2881, and https://github.com/pyinstaller/pyinstaller/issues/2125.

**Closed by pietermarsman** 2020-01-22 21:41 UTC
Labels: type: bug
