### ISSUE TITLE
convert to tag does not work in python 3 

### ISSUE THREAD

**Issue by johnsonice** [pdfminer/pdfminer.six#49] opened 2017-03-08 22:36 UTC
I am trying to convert PDF to tag file. It worked perfected fine in python 2. Tried the same thing in python 3, getting this error, any workaround?

```python
/home/ubuntu/anaconda3/envs/py35/lib/python3.5/site-packages/pdfminer.six-20170119-py3.5.egg/pdfminer/utils.py in make_compat_str(in_str)
     24 def make_compat_str(in_str):
     25     "In Py2, does nothing. In Py3, converts to string, guessing encoding."
---> 26     assert isinstance(in_str, (bytes, str, unicode))
     27     if six.PY3 and isinstance(in_str, bytes):
     28         enc = chardet.detect(in_str)

AssertionError:
```

**Comment by goulu** [comment] 2017-04-18 15:14
can anyone add a test to reproduce this please ? thanks !

**Comment by bittner** [comment] 2017-04-23 14:51
@johnsonice It looks like the error message is incomplete. Can you add the missing pieces, and fix the markup using ` ``` python` (which starts a multiline code block)?

**Comment by marine9357** [comment] 2017-08-21 12:36
I'm trying to do it as well, here's the error I get : 

`  File "C:\Users\Marine\Anaconda3\lib\site-packages\pdfminer\tools\pdf2txt.py", line 114, in main
    interpreter.process_page(page)
  File "C:\Users\Marine\Anaconda3\lib\site-packages\pdfminer\pdfinterp.py", line 851, in process_page
    self.device.begin_page(page, ctm)
  File "C:\Users\Marine\Anaconda3\lib\site-packages\pdfminer\pdfdevice.py", line 155, in begin_page
    self.outfp.write(utils.make_compat_bytes(output))
TypeError: write() argument must be str, not bytes`

I launched the command like this : 

`pdf2txt.py  -c UTF-8 -o artscient -t tag structure_article_scientifique.pdf`

Could it be a problem with the codec value? I also tried to remove the codec parameter, the same error appears..

**Comment by TamasNeumer** [comment] 2017-09-13 07:38
Having the same issue both on python2 and python3.6

**Comment by pietermarsman** [comment] 2019-10-16 14:20
Closing this because there is nothing reproducible. Feel free to reopen if the problem still exists. 

I've tested if the function behaves correctly on Python3.7 and it does. 

```python
def test_bytes(self):
    s = 'Hello World!'
    b = s.encode()
    ret = make_compat_str(b)
    assert_equal(s, ret)

def test_str(self):
    s = 'Hello World!'
    ret = make_compat_str(s)
    assert_equal(s, ret)
```

**Closed by pietermarsman** 2019-10-16 14:20 UTC
Labels: bug, help wanted
