### ISSUE TITLE
Conversion PDF to XML mixes up some words

### ISSUE THREAD

**Issue by dersuchendee** [pdfminer/pdfminer.six#424] opened 2020-05-12 07:13 UTC
I have a PDF document that has to be converted into XML, [here](https://drive.google.com/file/d/1Y0n7fWMX7jP_HaVgZMgk8S9gufZCXaoC/view).

But some words/sentences are in the wrong place.

This is my code:

```
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import HTMLConverter,TextConverter,XMLConverter
from pdfminer.layout import LAParams
from pdfminer.pdfpage import PDFPage
import io

def convert(case, pdfpath, targetfilepath, pages=100):
    if not pages: pagenums = set();
    else:         pagenums = set(pages);
    manager = PDFResourceManager()
    codec = 'utf-8'
    caching = True
    laparams = LAParams(all_texts=True)
    laparams.boxes_flow = -0.2
    #laparams.paragraph_indent = 0.2
    laparams.detect_vertical = False
    # laparams.heuristic_word_margin = 0.03
    laparams.word_margin = 0.2
    laparams.line_margin = 0.2
    laparams.char_margin = 100.0



    if case == 'text':
        output = io.StringIO()
        converter = TextConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'HTML':
        output = io.BytesIO()
        converter = HTMLConverter(manager, output, codec=codec, laparams=LAParams())
    if case == 'XML':
        output = io.BytesIO()
        converter = XMLConverter(manager, output, codec=codec, laparams= laparams)

    interpreter = PDFPageInterpreter(manager, converter)
    infile = open(pdfpath, 'rb')

    for page in PDFPage.get_pages(infile, pagenums,caching=caching, check_extractable=True):
        interpreter.process_page(page)

    convertedPDF = output.getvalue()

    infile.close(); converter.close(); output.close()

    convertedFile = open(targetfilepath, 'wb')
    convertedFile.write(convertedPDF)
    convertedFile.close()

print(convert('XML', 'sposipromessi3.pdf', 'sposipromessi3.xml', pages=None))





```
I don't know what I have to do to fix it, I tried setting up LAParams many times but with no success.

**Comment by pietermarsman** [comment] 2020-05-16 14:20
Closing because duplicate of #417

**Closed by pietermarsman** 2020-05-16 14:20 UTC
