### ISSUE TITLE
Can we add the functionality to return the 'Font Size' from pdfminer.layout.LTChar class?

### ISSUE THREAD

**Issue by abhibisht89** [pdfminer/pdfminer.six#211] opened 2018-11-15 12:35 UTC
Can we add this functionality. As this would be helpful for separating out different sections and finding out the continuation of text in a line in the pdf.
I have check the code from LTChar class in layout.py file and see that we have "fontsize" available there.
As in the same class we have get_text() also. same way we can have get_font_size().

Is there a reason why we are not returning "fontsize"?

**Comment by jbarlow83** [comment] 2018-11-27 10:04
You can read the instance variable LTChar.size, which is the size in page coordinates as determined by pdfminer. .fontsize is the size in text coordinates, which might differ.

You're allowed to read public instance variables.

**Comment by abhibisht89** [comment] 2018-11-27 11:51
yeah, size is different from font size , which I have analysed. However there is  a variable **fontsize** also available in the same class **LTChar** but that is no public instance variable. Why is that so?

**Comment by agargara** [comment] 2018-12-06 05:10
Duplicate of [this issue.](https://github.com/pdfminer/pdfminer.six/issues/202) As noted there, an easy fix is to add 

    self.fontsize = fontsize

to the `__init__` method of `class LTChar`.

**Comment by pietermarsman** [comment] 2019-11-10 15:02
Closing because it is a duplicate of #202

**Closed** 2019-11-10 15:02 UTC
Labels: type: enhancement
