### ISSUE TITLE
ImageWriter save FLATE_DECODE image as BMP makes the output file corrupt

### ISSUE THREAD

**Issue by dotrunghieu96** [pdfminer/pdfminer.six#916] opened 2023-11-08 02:56 UTC
**Bug report**

Thanks for finding the bug! To help us fix it, please make sure that you 
include the following information:

- A description of the bug:
  ImageWriter priortized BMP over FLATE_DECODE so some image in my PDF is saved as bmp directly, which caused them to corrupt.

- Steps to reproduce the bug. Try to minimize the number of steps needed. 
  Include the command and/or script that you use. Also include the PDF that 
  you use.:
  - Load the LTPage loaded from the PDF Page
  - In the LTPage, find the LTImage and save them with ImageWriter
 
- If relevant, include the output and/or error stacktrace: Some FLATE_DECODE image is saved as bmp and cannot be opened

**Comment by pietermarsman** [comment] 2023-12-22 20:55
Hi @dotrunghieu96,

Thanks for the bug report and the corresponding PR. 

Could you share a PDF and some code that you use to reproduce this bug? That will allow me to understand the impact of your suggested change better.

**Comment by dotrunghieu96** [comment] 2023-12-25 03:55
Hi @pietermarsman, this is the file that I used 
[GitGuide.pdf](https://github.com/pdfminer/pdfminer.six/files/13763728/GitGuide.pdf)

In code, first I was parsing the LTObjects via pages

```
from pdfminer.pdfpage import PDFPage
from pdfminer.pdfparser import PDFParser
# open the pdf file
fp = open(pdf_doc, "rb")
# create a parser object associated with the file object
parser = PDFParser(fp)
# create a PDFDocument object that stores the document structure
doc = PDFDocument(parser)
# connect the parser and document objects
parser.set_document(doc)
```

Then parse the LTObjects

```
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
for i, page in enumerate(PDFPage.create_pages(doc)):
    print("parsing pages:", i + 1, flush=True)
    interpreter.process_page(page)
    # receive the LTPage object for this page
    layout = device.get_result()
    for lt_obj in layout:
         if isinstance(lt_obj, LTImage):
            saved_file = save_image(lt_obj, page_number, images_folder)
```

In `save_image`, I used the `ImageWriter` class:
```
from pdfminer.image import ImageWriter

def save_image(lt_image: LTImage, page_number, images_folder):
    image_writer = ImageWriter(images_folder)
    file_name = image_writer.export_image(lt_image)
```

The problem here is that the images in the PDF are FLATE_DECODE, but ImageWriter saved them as `.bmp` image, which corrupt them.

So I moved FLATE_DECODE to a higher priority so that the _save_bytes() method is used first, and saved the image as ".jpg" which have the saved images perfectly viewable.

**Comment by pietermarsman** [comment] 2024-01-16 20:43
Fixed by #937

**Closed** 2024-01-16 20:49 UTC

**Comment by pietermarsman** [comment] 2024-01-16 20:51
Let me know if the issue is still there for you, and we can reopen this issue. In that case, could you specify what you mean by "corrupt"?

**Comment by iraykhel** [comment] 2024-02-28 20:55
Yup, extracting .bmp doesn't work. 
Crashes here:
if params and "Predictor" in params:
TypeError: argument of type 'PDFObjRef' is not iterable

If this check is bypassed, extracted .bmp is corrupted.

```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTFigure, LTImage
from pdfminer.image import ImageWriter

pdf_path = 'path/to/bmp'
W = ImageWriter('path/to/storage')
pages = extract_pages(pdf_path)
for element in pages.__next__():
    if isinstance(element, LTFigure):
        for sub in element:
            if isinstance(sub, LTImage):
                W.export_image(sub)
```

[bmpsample2.pdf](https://github.com/pdfminer/pdfminer.six/files/14439877/bmpsample2.pdf)
