### ISSUE TITLE
Helvetica typeface not recognized

### ISSUE THREAD

**Issue by SherlockHua1995** [pdfminer/pdfminer.six#482] opened 2020-08-31 05:30 UTC
**Bug report**

Thanks for finding the bug! To help us fix it, please make sure that you 
include the following information:

- A description of the bug
- Steps to reproduce the bug. Try to minimize the number of steps needed. 
  Include the command and/or script that you use. Also include the PDF that 
  you use.
- If relevant, include the output and/or error stacktrace. 

Hello，I am applying pdfplumber to parse the pdf with Helvetica and STSong-light typeface but I got all blanks
[‘ ‘，‘ ‘，‘ ‘，‘ ‘]
table = page.extract_table()

pdfminer.six cannot recognize the characters？Any solutions？
pdfminer.six 20200517
pdfplumber 0.5.23
Python37
Thanks.

**Comment by pietermarsman** [comment] 2020-09-12 13:09
Hi @SherlockHua1995,

Can you share the PDF and the code you are using?

**Comment by pietermarsman** [comment] 2020-10-18 10:41
Closing this because not reproducible (no example pdf).

**Closed by pietermarsman** 2020-10-18 10:41 UTC
Labels: type:anomaly
