### ISSUE TITLE
Use a more universal line ending

### ISSUE THREAD

**Issue by charlesreid1** [pdfminer/pdfminer.six#149] opened 2018-06-04 05:26 UTC
After successfully running `pip install pdf2txt.six` I see the following error when I run the program on the sample:

```
$ pdf2txt.six sample.pdf
env: python\r: No such file or directory
```

This is caused by the file being saved in Windows. Please replace `\r\n` with `\n` as it is more universal.

**Comment by charlesreid1** [comment] 2018-06-04 05:27
Related issue that gives a temporary workaround: #145

Discussion in this thread is about a permanent fix.

**Comment by RolandColored** [comment] 2018-06-21 08:15
Looks like a good idea. Can you open a pull request for this?

**Comment by charlesreid1** [comment] 2018-06-21 19:21
See #160

**Comment by pietermarsman** [comment] 2019-10-13 17:22
Duplicate of #27

**Closed by pietermarsman** 2019-10-13 17:22 UTC
