### ISSUE TITLE
how to program with pdfminer.six

### ISSUE THREAD

**Issue by netbusxp** [pdfminer/pdfminer.six#309] opened 2019-10-20 16:23 UTC
i have been programming with pdfminer3k because there are some examples in the internet
but for somg reason i need CJK support so i install pdfminer.six
i found there are all command functions 
is there any coding sample that programming with pdfminer.six?
attatch my code in pdfminer3k
```python
from pdfminer.pdfparser import PDFParser,PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LTTextBoxHorizontal,LAParams,LTFigure
from pdfminer.pdfinterp import PDFTextExtractionNotAllowed
def get_mulu_text1(pdf_path):
    fp = open(pdf_path, 'rb')  

    praser = PDFParser(fp)

    doc = PDFDocument()

    praser.set_document(doc)
    doc.set_parser(praser)

    doc.initialize()

    if not doc.is_extractable:
        raise PDFTextExtractionNotAllowed
    else:
        rsrcmgr = PDFResourceManager()
        laparams = LAParams()
        device = PDFPageAggregator(rsrcmgr, laparams=laparams)
        interpreter = PDFPageInterpreter(rsrcmgr, device)
        for page in doc.get_pages():  # doc.get_pages() 获取page列表
            interpreter.process_page(page)
            layout = device.get_result()
            if (layout.pageid <10):
                for x in layout:
                    if (isinstance(x, LTTextBoxHorizontal)):
                        results = x.get_text()
                        print(results)
                        print('-')
            else:
                break
```

above codes seems work in pdfminer3k,but not work in pdfminer.six because of some library changed name or other reasons
is there any example for me like above to use pdfminer.six extracting informations with python?
thanks everyone!!
 -------------------------------------------------------------
new progress
i have found the solution [https://dzone.com/articles/exporting-data-from-pdfs-with-python](url)
now i'm at work after work i will try~

**Comment by pietermarsman** [comment] 2019-10-20 17:55
Hi @netbusxp, thanks for your question. Could you share the pdf that you are using with this code? This would make it easy for others to reproduce the issue.

And about the issue: what is it? :smile: you don't mention any specifics about the problem, only that there is one.

**Comment by netbusxp** [comment] 2019-10-21 01:06
@pietermarsman above code is used for pdfminer3k (i have search these days and found that pdfminer3k is a extent library wrtiien by others--also in github)
and here is the pdf 
[2019-03-16-600508-上海能源：2018年年度报告.PDF](https://github.com/pdfminer/pdfminer.six/files/3748603/2019-03-16-600508-.2018.PDF)
my task is to recongnize the catalogs(in this file in page 3) and extarct information by catalog name(in this file i extract 12 content by catalog name ) saving in a excel,i have to handle 40000+ pdfs like above so i have to program with python with it
above code is worked in pdfminer3k(using pip install pdfminer3k) and can print first 10 pages results in command line,but the question is **pdfminer3k is not support CJK** ,so i changed to pdfminer.six
but i dont know how to program with six,the above codes is not work in six,because maybe the library name is different
what i need is **programming example to handle the pdf i uploaded** by python
only print the result in the command line is okay,if it is possible can add some conditions like page number\or print by texts not pages

**Comment by pietermarsman** [comment] 2019-10-21 20:34
I've adjusted your example a little and reduced the code a bit. The following example works for me. Does it also work for you? 

```python
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams
from pdfminer.layout import LTTextBoxHorizontal
from pdfminer.pdfinterp import PDFPageInterpreter
from pdfminer.pdfinterp import PDFResourceManager
from pdfminer.pdfpage import PDFPage


def get_mulu_text1(pdf_path):
    resource_manager = PDFResourceManager()
    page_aggregator = PDFPageAggregator(resource_manager, laparams=LAParams())
    page_interpreter = PDFPageInterpreter(resource_manager, page_aggregator)

    with open(pdf_path, 'rb') as fin:
        for page in PDFPage.get_pages(fin, pagenos=[3]):
            page_interpreter.process_page(page)
            layout = page_aggregator.get_result()
            for element in layout:
                if isinstance(element, LTTextBoxHorizontal):
                    print(element.get_text())


get_mulu_text1('2019-03-16-600508-.2018.PDF')
```

Note that:

- It only extracts text from page 3 because I know that this is the page you are interested in. You can parse all pages by removing `pagenos=[3]`. 
- The output are all characters that I can't read but I'm pretty sure that it parses the CJK characters correctly.

**Comment by pietermarsman** [comment] 2019-10-21 20:35
I'm closing this question because I am considering it answered. Feel free to reopen if you keep having problems.

**Closed by pietermarsman** 2019-10-21 20:35 UTC
Labels: question

**Comment by netbusxp** [comment] 2019-10-22 00:47
> I've adjusted your example a little and reduced the code a bit. The following example works for me. Does it also work for you?
> 
> ```python
> from pdfminer.converter import PDFPageAggregator
> from pdfminer.layout import LAParams
> from pdfminer.layout import LTTextBoxHorizontal
> from pdfminer.pdfinterp import PDFPageInterpreter
> from pdfminer.pdfinterp import PDFResourceManager
> from pdfminer.pdfpage import PDFPage
> 
> 
> def get_mulu_text1(pdf_path):
>     resource_manager = PDFResourceManager()
>     page_aggregator = PDFPageAggregator(resource_manager, laparams=LAParams())
>     page_interpreter = PDFPageInterpreter(resource_manager, page_aggregator)
> 
>     with open(pdf_path, 'rb') as fin:
>         for page in PDFPage.get_pages(fin, pagenos=[3]):
>             page_interpreter.process_page(page)
>             layout = page_aggregator.get_result()
>             for element in layout:
>                 if isinstance(element, LTTextBoxHorizontal):
>                     print(element.get_text())
> 
> 
> get_mulu_text1('2019-03-16-600508-.2018.PDF')
> ```
> 
> Note that:
> 
> * It only extracts text from page 3 because I know that this is the page you are interested in. You can parse all pages by removing `pagenos=[3]`.
> * The output are all characters that I can't read but I'm pretty sure that it parses the CJK characters correctly.

Yesterday i also finished this question,but your code seems better than me,i am working now,afterwork i will try 
thanks very much!!!!!!!! this problem troubles me nearly 20days~
another question:is there any manual or guideline about pdfminer.six 
reading the source code semms a little difficult for me

**Comment by pietermarsman** [comment] 2019-10-22 06:14
You can checkout the old instructions, the have rebirth on read the docs: https://pdfminer-docs.readthedocs.io/programming.html

Our documentation is still lacking. We hope to fix that soon.

**Comment by netbusxp** [comment] 2019-10-22 06:31
okay thanks i will try

**Comment by netbusxp** [comment] 2019-11-17 15:07
@pietermarsman hi these days when i extract pdf i met a question
[009-000682-东方电子：2009年年度报告.PDF](https://github.com/pdfminer/pdfminer.six/files/3855705/009-000682-.2009.PDF)
Traceback (most recent call last):
  File "D:/upan/pdfminer.six-20181108/tools/trans.py", line 37, in <module>
    get_mulu_text1(r'009-000682-东方电子：2009年年度报告.PDF')
  File "D:/upan/pdfminer.six-20181108/tools/trans.py", line 25, in get_mulu_text1
    for page in PDFPage.get_pages(fin, pagenos=[3]):
  File "D:\python\lib\site-packages\pdfminer.six-20181108-py3.7.egg\pdfminer\pdfpage.py", line 129, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)
  File "D:\python\lib\site-packages\pdfminer.six-20181108-py3.7.egg\pdfminer\pdfdocument.py", line 566, in __init__
    xref.load(parser)
  File "D:\python\lib\site-packages\pdfminer.six-20181108-py3.7.egg\pdfminer\pdfdocument.py", line 195, in load
    (_, obj) = parser.nextobject()
  File "D:\python\lib\site-packages\pdfminer.six-20181108-py3.7.egg\pdfminer\psparser.py", line 574, in nextobject
    (pos, token) = self.nexttoken()
  File "D:\python\lib\site-packages\pdfminer.six-20181108-py3.7.egg\pdfminer\psparser.py", line 500, in nexttoken
    self.fillbuf()
  File "D:\python\lib\site-packages\pdfminer.six-20181108-py3.7.egg\pdfminer\psparser.py", line 230, in fillbuf
    raise PSEOF('Unexpected EOF')
pdfminer.psparser.PSEOF: Unexpected EOF

so what is this meaning or what shall i do
may be the form of the file have some problem or i'm lack of some libraries?

**Comment by pietermarsman** [comment] 2019-11-17 15:16
It probably means the pdf is broken. Pdfminer.six is robust for some variation in pdf's but it has its limits. 

If this also happens to other pdf's or if this pdf is important to you, please create a new issue for it.
