### ISSUE TITLE
Version 20200517 cannot extract correct text from pdf file (version: pdf-1.2) but Version 20181108 can

### ISSUE THREAD

**Issue by cjmqwerty** [pdfminer/pdfminer.six#430] opened 2020-05-21 06:40 UTC
Here is a pdf file (pdf-1.2):
http://disc.static.szse.cn/download/disc/disk01/finalpage/2001-09-18/0b1e3780-f338-4761-a796-92b9c7685100.PDF
There are many Chinese characters but I can only get some numbers after using pdfminer.highlevel.extract_text to analyse this file when the pdfminer.six version is the newest(20200517). 
But if I changed pdfminer.six version to 20181108 it works fine. 
I can't switch the package version every time I find the extration incorrect. So could you please check this situation and fix it?
Thank you for your contributions.

**Comment by pietermarsman** [comment] 2020-05-21 15:05
I did a `git bisect` and the issue was introduced in fa400431f571de9197ab72ffc5dd9f7d76826474. 

Closing this as a duplicate of #391. 

@cjmqwerty you can comment on #391 saying that you also experience this issue.

**Closed by pietermarsman** 2020-05-21 15:05 UTC
Labels: component:characters, type: bug
