### ISSUE TITLE
problem with crypto

### ISSUE THREAD

**Issue by fran6w** [pdfminer/pdfminer.six#143] opened 2018-04-15 16:11 UTC
Hi,
I am trying to run an .exe built with py2exe on a piece of code that imports pdfminer.six.
Some problems occur when importing crypto libs, see below.
As I do not use crypted PDF files, why do you systematically import crypto? Wouldn't it be possible to perform lazy crypto import only when needed?
Best,

```commandline
  File "blueprint.py", line 13, in <module>
    from pdfminer.pdfpage import PDFPage
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Anaconda3\lib\site-packages\pdfminer\pdfpage.py", line 11, in <module>
    from .pdfdocument import PDFDocument
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Anaconda3\lib\site-packages\pdfminer\pdfdocument.py", line 12, in <mo
dule>
    from Crypto.Cipher import ARC4
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Anaconda3\lib\site-packages\Crypto\Cipher\__init__.py", line 3, in <m
odule>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "C:\Anaconda3\lib\site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in
<module>
  File "C:\Anaconda3\lib\site-packages\Crypto\Util\_raw_api.py", line 258, in lo
ad_pycryptodome_raw_lib
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.py
d': cannot load library ...\dist\blueprint.exe\Crypto\Util\..\Cipher\_raw_ecb.pyd: error 0x7e
```

**Comment by RolandColored** [comment] 2018-06-01 13:33
I have no idea regarding the initial problem. But I had no luck generating exe files using py2exe in general, which resulted in similar problems. Using pyinstaller did the trick for me.

**Comment by dickkniep** [comment] 2018-06-19 15:46
The same problem occurs with pyinstaller. See https://github.com/pyinstaller/pyinstaller/issues/2881 It seems that the issue is that reference is to the old Crypto package which should be replaced by direct reference to the new package pycryptodome.

**Comment by ankit28jindal** [comment] 2018-07-03 04:37
I am facing same issue while using pdfminer.six on aws lambdas. Any solution to this issue?

**Comment by pietermarsman** [comment] 2019-11-17 14:41
>  It seems that the issue is that reference is to the old Crypto package which should be replaced by direct reference to the new package pycryptodome.

The requirement for pycrypto was updated to pycryptodome in fe21725f07ee9511a5c5536d34c18194c12989ee. Does this fix the problem? What command are you using to test this?

**Comment by pietermarsman** [comment] 2020-01-14 21:17
Closing this because this is an issue with pyinstaller, py2exe and/or pycrypto (see e.g. the earlier mentioned issue https://github.com/pyinstaller/pyinstaller/issues/2881, and https://github.com/pyinstaller/pyinstaller/issues/2125). 

Feel free to point out if I am wrong.

**Closed by pietermarsman** 2020-01-14 21:17 UTC
Labels: type: bug
