### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jjhuff** [pdfminer/pdfminer.six#404] opened 2020-03-24 16:45 UTC
Example url: http://www.accessdata.fda.gov/drugsatfda_docs/label/2019/021107s029lbl.pdf

Backtrace:
```
  File "amplion/utils/pdf.py", line 29, in extract_pdf_text_from_fp
    interpreter.process_page(page)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 896, in process_page
    self.device.end_page(page)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/converter.py", line 49, in end_page
    self.cur_item.analyze(self.laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 733, in analyze
    group.analyze(laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 501, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 350, in analyze
    obj.analyze(laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 501, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 350, in analyze
    obj.analyze(laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 501, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 350, in analyze
    obj.analyze(laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 501, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 350, in analyze
    obj.analyze(laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 501, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 350, in analyze
    obj.analyze(laparams)
  File "/usr/local/lib/python3.7/site-packages/pdfminer/layout.py", line 501, in analyze
    LTTextGroup.analyze(self, laparams)
.....
```

**Comment by pietermarsman** [comment] 2020-03-24 22:03
Hi @jjhuff, thanks for raising this issue!

What version of pdfminer.six are you using? And what command are you using?

**Comment by jjhuff** [comment] 2020-03-24 22:19
I was using 20200124
The code is more or less this, but I believe it should repo with pdf2txt
```
    laparams = LAParams()
    rsrcmgr = PDFResourceManager()
    with io.StringIO() as outfp:
        device = TextConverter(rsrcmgr, outfp, laparams=laparams)
        interpreter = PDFPageInterpreter(rsrcmgr, device)
        for page in PDFPage.get_pages(fp):
            interpreter.process_page(page)
        device.close()
        text = outfp.getvalue()
```

**Comment by pietermarsman** [comment] 2020-03-26 21:38
I can replicate this using `pdf2txt.py`. The problem happens on page 5. 

You can fix your problem by increasing the `line_margin`. Setting it to 2.0 fixes it for me. This merges more lines into text-boxes and makes the next analyse step (the one with the recursion error) easier.

I'm not sure what causes the problem so I would like to keep this issue open until we figure out if there is something we can do about it.

**Comment by metalogueur** [comment] 2020-10-19 21:10
Just ran into that same bug using version 20200726... Will wait for the issue to be solved... Thanks for your hard work!

**Comment by jonaswinkler** [comment] 2021-02-20 23:45
I've also encountered this issue on a document after calling `extract_text` on version `20201018`

```
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/high_level.py", line 121, in extract_text
    interpreter.process_page(page)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 896, in process_page
    self.device.end_page(page)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/converter.py", line 50, in end_page
    self.cur_item.analyze(self.laparams)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/layout.py", line 814, in analyze
    group.analyze(laparams)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/layout.py", line 575, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/layout.py", line 362, in analyze
    obj.analyze(laparams)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/layout.py", line 575, in analyze
    LTTextGroup.analyze(self, laparams)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/layout.py", line 362, in analyze
    obj.analyze(laparams)
  File "/home/jonas/.local/share/virtualenvs/paperless-RxYopU_u/lib/python3.9/site-packages/pdfminer/layout.py", line 575, in analyze
    LTTextGroup.analyze(self, laparams)
```

I believe that this is the same issue and the different line numers are caused by changes somewhere else in that file.

**Comment by rain01** [comment] 2022-03-04 22:03
Recently I have started seeing this issue in my error logs.
I am using `pdfminer.six==20211012` with:
```
<LAParams: char_margin=2.0, line_margin=0.1, word_margin=0.1 all_texts=True>
```
Increasing line_margin helped as a temporary solution, any idea if there is a better way?

**Comment by pietermarsman** [comment] 2022-03-20 16:22
Fixed in the current version. 

The issue was partially fixed by @0xabu in https://github.com/pdfminer/pdfminer.six/pull/659. After this PR pdf2txt.py run indefinitely on page 5. 

This issue was then completely fixed by @jwyawney in https://github.com/pdfminer/pdfminer.six/pull/689. I guess by ignoring empty characters the layout algorithm does generate less `LTTextLine` and therefore the grouping is easier. Or something along that lines.

**Closed by pietermarsman** 2022-03-20 16:22 UTC
Labels: type: bug

**Comment by Rumpelcita** [comment] 2022-09-22 14:59
Hi, I'm still running into this issue on version `20220524` of pdfminer.six. I can't provide the pdf that causes the issue since it needs to be anonymized, but these are the LAParams we're using for pdfminer:

```
LAParams(
    line_overlap= 0.5,
    char_margin= 1.1,
    word_margin= 0.2,
    line_margin= 0.5,
    boxes_flow= 0.5,
    all_texts=True,
        )
```

Traceback:

```
RecursionError: maximum recursion depth exceeded
(245 additional frame(s) were not displayed)
...
  File "pdfminer/layout.py", line 705, in analyze
    super().analyze(laparams)
  File "pdfminer/layout.py", line 439, in analyze
    obj.analyze(laparams)
  File "pdfminer/layout.py", line 705, in analyze
    super().analyze(laparams)
  File "pdfminer/layout.py", line 439, in analyze
    obj.analyze(laparams)
  File "pdfminer/layout.py", line 439, in analyze
    obj.analyze(laparams)

maximum recursion depth exceeded
```
