### ISSUE TITLE
question about potential bug reports

### ISSUE THREAD

**Issue by alvercau** [pdfminer/pdfminer.six#248] opened 2019-05-22 11:27 UTC
Hi

We might have found some bugs in pdfminer.six, but they can only be replicated on some documents, for which we have several examples. However, we are not allowed to share the documents with anyone. How can we open an issue in this case? Creating a document to be able to replicate the bug is very hard, because we do not know what exactly is different about the documents giving issues.

Thanks!

**Comment by BLMeltdown** [comment] 2019-06-17 08:53
Can't you extract an innocuous page of the document and replicate the bug?

**Comment by pietermarsman** [comment] 2019-07-09 16:28
You can open the pdf's with a text editor like atom, notepad++ or sublime and edit the content of the pdf. You could try to identify and remove the (possible binary) content you try to don't want to share. 

Without an example pdf there is, indeed, not much that we can do.

**Comment by pietermarsman** [comment] 2019-10-12 22:37
Another thing you can do is to open an issue without an example pdf. This is not recommended because it makes it difficult to replicate. However, the error message might be enough to identify the root cause and fix it. Also, other people might recognize the bug and have a pdf available that they can share.

I'm closing this issue as there is nothing to do here. Feel free to reopen it if you have other specific questions about this topic.

**Closed by pietermarsman** 2019-10-12 22:37 UTC
