### ISSUE TITLE
all_texts=False result in missing newlines

### ISSUE THREAD

**Issue by d362622563** [pdfminer/pdfminer.six#446] opened 2020-06-22 02:48 UTC
I am trying to process a pdf document with following code:
`text=extract_text(pdf_file=open('***.pdf','rb'),laparams=LAParams(all_texts=True))`

The extracted text are in correct format but wrong sequence:
![all_texts=True](https://user-images.githubusercontent.com/67249800/85243783-53e65a00-b475-11ea-9c8b-dacb0fa2d078.jpg)

When I change the code into:
`text=extract_text(pdf_file=open('***.pdf','rb'),laparams=LAParams(all_texts=False))`

The extracted text are in correct sequence but the newlines are missing:
![all_texts=False](https://user-images.githubusercontent.com/67249800/85243825-75dfdc80-b475-11ea-8c6a-d5a7d27d3840.jpg)

Can anyone advise how does all_texts=True/False affect the newlines in my pdf or is there a better way to work it out? Thanks!

**Comment by jstockwin** [comment] 2020-06-23 14:48
@d362622563 Is there any chance you could provide the PDF to test this?

`all_texts` should not change this behaviour IIRC, since it's only about whether to perform layout analysis on text in figures. That said, it could be that some of your text is indeed inside figures...

You mention that the text is in the correct/incorrect sequence. Another thing that can change this is `boxes_flow`. In the most recent version of pdfminer you can try passing `boxes_flow=None`, which will disable the advanced layout analysis and instead return elements based on where they are on the page.

**Comment by d362622563** [comment] 2020-06-24 01:16
> @d362622563 Is there any chance you could provide the PDF to test this?
> 
> `all_texts` should not change this behaviour IIRC, since it's only about whether to perform layout analysis on text in figures. That said, it could be that some of your text is indeed inside figures...
> 
> You mention that the text is in the correct/incorrect sequence. Another thing that can change this is `boxes_flow`. In the most recent version of pdfminer you can try passing `boxes_flow=None`, which will disable the advanced layout analysis and instead return elements based on where they are on the page.

Hi @jstockwin, thanks for your reply. I cannot share the whole document since it is confidential, however I have extracted one page with only one paragraph to test the code, appreciate if you could find a way to keep the newlines when all_texts=False.

[ENV.pdf](https://github.com/pdfminer/pdfminer.six/files/4822673/ENV.pdf)

**Comment by jstockwin** [comment] 2020-06-24 07:51
Hi @d362622563, so I can see that actually all the text in your PDF is inside a figure. This is a bit strange, but it simply due to how the PDF is structured.

The reason, therefore, that you're not getting any newlines with `all_texts=False` is because layout analysis is not being performed on this text, and hence the newlines are not inserted.

You want layout analysis for the new lines, so need `all_texts=False`. If they're coming in an unexpected order, you could try disabling the advanced layout analysis (which tries to hierarchically group text boxes based on how close they are), but setting `boxes_flow=None`. I think that should fix the ordering issue for you (although can't check this with the single paragraph you provided).

It's perhaps slightly strange that the text from within a figure is included in the output when `all_texts=False`, i.e. it hasn't had layout analysis performed, however, I suppose this is probably expected behaviour (@pietermarsman?).

**Comment by d362622563** [comment] 2020-06-25 00:59
Hi @jstockwin, thanks a lot for your advice, after applying boxes_flow=None, the results are much better!

**Comment by jstockwin** [comment] 2020-06-25 08:47
Glad to help @d362622563. If you're happy with your output now, would you mind closing this issue?

**Closed** 2020-06-26 00:45 UTC

**Comment by pietermarsman** [comment] 2020-07-05 11:09
> It's perhaps slightly strange that the text from within a figure is included in the output when all_texts=False, i.e. it hasn't had layout analysis performed, however, I suppose this is probably expected behaviour (@pietermarsman?).

I would expect the layout analysis to be applied on the figure text as well
