### ISSUE TITLE
script in documents does not run properly

### ISSUE THREAD

**Issue by misokol-earthlink** [pdfminer/pdfminer.six#741] opened 2022-03-29 17:55 UTC
In the pdfminer.six documentation section 1.2.2 shows a script to extract elements from an Acro Form.   the initial lines of the script contain imports such as from pdfminer.pdfparser import PDFParser etc.  There are five lines of imports.  When I include all of the code displayed in a Python script and attempt to run the script from command line, I get messages saying no module named pdfminer.pdfparser found;   pdfminer is not a package.    However if I open Python and  enter each line in the window,  the code is accepted without errors.   So the syntax works for an interpreter but not from a script file.  Screen shot of errors attached
[Errors.pdf](https://github.com/pdfminer/pdfminer.six/files/8373853/Errors.pdf)

**Comment by pietermarsman** [comment] 2022-04-04 20:04
This problem is often caused by having multiple pdfminer and pdfminer.six installations. 

Try to remove all of the pdfminer's from your system and then only install pdfminer.six. 

I'm closing this issue because it is not an issue with pdfminer.six. But feel free to reply if reinstalling does not work.

**Closed by pietermarsman** 2022-04-04 20:04 UTC
Labels: type: question
