### ISSUE TITLE
PSEOF: Unexpected EOF

### ISSUE THREAD

**Issue by mkw18** [pdfminer/pdfminer.six#448] opened 2020-06-27 12:34 UTC
```
import io
import sys
import importlib
importlib.reload(sys)
 
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator, TextConverter
from pdfminer.layout import *
from pdfminer.pdfpage import PDFTextExtractionNotAllowed, PDFPage

def extract_text_by_page(pdf_path):
    with open(pdf_path, 'rb') as fh:
        for page in PDFPage.get_pages(fh, caching = True, check_extractable=True):
            resource_manager = PDFResourceManager()
            fake_file_handle = io.StringIO()
            converter = TextConverter(resource_manager, fake_file_handle)
            page_interpreter = PDFPageInterpreter(resource_manager, converter)
            page_interpreter.process_page(page)
            
            text = fake_file_handle.getvalue()
            yield text
            
            converter.close()
            fake_file_handle.close()
            
def extract_text(pdf_path):
    for page in extract_text_by_page(pdf_path):
        print(page)

if __name__ == '__main__':
  pdf_path = r'C:\Users\SC\Documents\Sophomoreii\SRT\clinic\pdf-clinic\abc.pdf'
  extract_text(pdf_path)
```

When I run the code above, I encounter the following errors:

Traceback (most recent call last):

  File "C:\Users\SC\Documents\Sophomoreii\SRT\clinic\pdf_clinic.py", line 82, in <module>
    extract_text(pdf_path)

  File "C:\Users\SC\Documents\Sophomoreii\SRT\clinic\pdf_clinic.py", line 76, in extract_text
    for page in extract_text_by_page(pdf_path):

  File "C:\Users\SC\Documents\Sophomoreii\SRT\clinic\pdf_clinic.py", line 62, in extract_text_by_page
    for page in PDFPage.get_pages(fh, caching = True, check_extractable=True):

  File "C:\Users\SC\Anaconda3\lib\site-packages\pdfminer\pdfpage.py", line 127, in get_pages
    doc = PDFDocument(parser, password=password, caching=caching)

  File "C:\Users\SC\Anaconda3\lib\site-packages\pdfminer\pdfdocument.py", line 554, in __init__
    xref.load(parser)

  File "C:\Users\SC\Anaconda3\lib\site-packages\pdfminer\pdfdocument.py", line 177, in load
    (_, obj) = parser.nextobject()

  File "C:\Users\SC\Anaconda3\lib\site-packages\pdfminer\psparser.py", line 567, in nextobject
    (pos, token) = self.nexttoken()

  File "C:\Users\SC\Anaconda3\lib\site-packages\pdfminer\psparser.py", line 493, in nexttoken
    self.fillbuf()

  File "C:\Users\SC\Anaconda3\lib\site-packages\pdfminer\psparser.py", line 221, in fillbuf
    raise PSEOF('Unexpected EOF')

PSEOF: Unexpected EOF

I have tried to install and uninstall the pdfminer.six, but it doesn't work. I tried to change the pdf document, but encountered the same error. How can I solve this problem?

**Comment by pietermarsman** [comment] 2020-06-29 18:38
Hi @mkw18, thanks for sharing the stacktrace and code. Can you include the PDF that you use such that we can reproduce this issue?

**Comment by pietermarsman** [comment] 2020-07-18 14:13
Closing this because not reproducible.

**Closed by pietermarsman** 2020-07-18 14:13 UTC

**Comment by swarup008** [comment] 2020-11-08 20:54
This problem occurs when there are **ATTACHMENTS** present within a pdf file.

I have provided a sample file in the below link:
[attachment_test.pdf](https://github.com/pdfminer/pdfminer.six/files/5507157/attachment_test.pdf)

Screenshot of an example file:
![image](https://user-images.githubusercontent.com/35597446/98484003-816c4e00-2232-11eb-9221-fb8ff64e76a2.png)

**Comment by noancloarec** [comment] 2021-04-20 12:44
I'm having the same bug, here is a reproducible example : 

```python
from pdfminer.high_level import extract_pages

list(extract_pages('unexpected_eof.pdf'))
```

[unexpected_eof.pdf](https://github.com/pdfminer/pdfminer.six/files/6343567/unexpected_eof.pdf)

**Comment by noancloarec** [comment] 2021-04-20 14:29
As a workaround, cleaning PDF with qpdf solved the problem .
