### ISSUE TITLE
/usr/bin/env: ‘python\r’: No such file or directory

### ISSUE THREAD

**Issue by donpellegrino** [pdfminer/pdfminer.six#27] opened 2016-07-16 19:46 UTC
pdf2txt.py fails to run with:

/usr/bin/env: ‘python\r’: No such file or directory

This appears to be due to a DOS carriage return in the shebang line. Running `dos2unix pdf2txt.py` appears to fix the issue.

Test environment:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial

pdfminer.six (20160614) - from PyPi via pip

Running in a virtualenv

$ virtualenv --version
15.0.1

$ python --version
Python 3.5.1+

**Comment by fabianhjr** [comment] 2016-07-23 00:34
Also got the problem, though code is different from release.

This is the git blame of the shebang.
```git
0ea08890 (Yusuke Shinyama       2013-10-17 23:05:27 +0900   1) #!/usr/bin/env python
1b47bed3 (Cathal Garvey         2015-05-17 21:08:57 +0100   2) """
1b47bed3 (Cathal Garvey         2015-05-17 21:08:57 +0100   3) Converts PDF text content (though not images containing text) to plain text, html, xml or "tags".
1b47bed3 (Cathal Garvey         2015-05-17 21:08:57 +0100   4) """
```

And this is the sha256sum of the git file
`8135d29311aad3367bef0f20a387caf87cd454d5c34025410d00c819910b7bf9  tools/pdf2txt.py`

and the sha256sum of the pypi release file
`2e11a11f3a81f58968c103cb7f0297637a726e2aa7d3cbb95eb4cb0e79ce0a6c  /usr/bin/pdf2txt.py`

and this is the sha256sum of the pypi release file when passed trough dos2unix
`8135d29311aad3367bef0f20a387caf87cd454d5c34025410d00c819910b7bf9  fileout`

So, something happened with the release; but the file is ok in git.
/cc @goulu

**Comment by jaraco** [comment] 2016-09-15 13:43
I believe this issue is the cause of the test failure in deanmalmgren/textract#116. I suspect that the release was made from a checkout using a tool that converts newlines or possibly that the packaging tools converted the newlines on the script when the release was cut on a Windows system. In either case, a new release is needed to resolve this issue.

If it would help, I could submit a PR to the .travis.yml file that would cut releases to PyPI automatically based on tagged commits (or you can adapt the concept from my [skeleton](https://github.com/jaraco/skeleton) project).

**Comment by gwk** [comment] 2016-11-15 14:57
First time user here, just hit this problem as well.

Also worth noting that the entire shebang is wrong, at least for a standard install on OSX. Python 3 is named `python3` so that it can coexist with Python 2.`pip3 install pdfminer.six` installs pdf2txt.py into the python 3 framework tree: /Library/Frameworks/Python.framework/Versions/3.5/bin/pdf2txt.py.

So the shebang line should be '/usr/bin/env python3\n', with no carriage return.

**Comment by deanmalmgren** [comment] 2016-11-15 15:21
was this was fixed in 0fdebc6739143e716a4cb8b7f26ecf012e314cfc?

**Comment by gwk** [comment] 2016-11-15 15:35
Just from looking at the diff, it appears *not* to be fixed. See this section:

https://github.com/goulu/pdfminer/commit/0fdebc6739143e716a4cb8b7f26ecf012e314cfc#diff-147654f85909c4dee04d20e37ebb576f

The shebang lines appear to have been removed from library code, but not from the tool scripts.

I believe the recommended solution to this problem is to use setuptools 'entry_points' and 'console_scripts' features of setup.py: http://setuptools.readthedocs.io/en/latest/setuptools.html#automatic-script-creation

This way setuptools will generate the top-level scripts that get installed into the python bin directory, with appropriate permissions and shebang. The generated script does some fancy resolution stuff and then calls a specified function, typically 'main' or equivalent. This will require moving things around a bit.

Hope that helps!

**Comment by deanmalmgren** [comment] 2016-11-15 18:45
Some good news: I was able to install directly from the current version using

```sh
pip install https://github.com/goulu/pdfminer/zipball/e6ad15af79a26c31f4e384d8427b375c93b03533#egg=pdfminer.six
```

I've confirmed this as [tests are now passing for textract](https://travis-ci.org/deanmalmgren/textract/builds/176133798) (hallelujah!). When a new version of `pdfminer.six` is released, I believe you can close this out @goulu.

Thanks for managing `pdfminer` and helping to merge many great ideas into the package!

**Comment by goulu** [comment] 2017-01-20 10:02
Well, I don't fully understand ... is this problem specific to OSX ? 
What should we do to release a package on PyPi that would install correctly for Python 3 and Python 2 on Win/Linux/OSX machines ?

**Comment by deanmalmgren** [comment] 2017-01-20 11:25
This is a problem with installing pdfminer.six in a virtualenv

**Comment by gwk** [comment] 2017-01-20 15:20
> Well, I don't fully understand ... is this problem specific to OSX ?

I only tried this with OSX, but my previous points should apply equally to any Unix environment.

If you want to migrate to using entry points, the basic idea is that you refactor each of the tools into a function in a module, and then map the name of the tool to that function. So setup.py would contain something like:

```
entry_points = {'console_scripts': [
    'pdf2txt=pdfminer.pdf2txt:main',
    ...
]},
```

In this configuration, pdf2txt.py is simply part of the pdfminer package. the `pdf2txt` executable is generated on install and calls `pdfminer.pdf2txt.main()`.

I'm sure there are other ways to do it, but I like this method because it plays well with pip developer mode: `pip3 install -e .`. In developer mode changes to the source code are immediately visible to the installed scripts.

**Comment by deanmalmgren** [comment] 2017-01-20 17:39
Oh. Sorry. I got confused. It is working for me in Ubuntu. I don't know if there is still a problem with this PR in other operating systems.

**Comment by bittner** [comment] 2017-04-23 14:13
Just a heads up, I've run `dos2unix` all the following files in PR #58

- `*.py`
- `*.md`
- `*.rst`
- `*.yml`
- `.gitignore`
- `Makefile`
- `MANIFEST.in`

... and the result is that only `.travis.yml` was still affected.

**Comment by anshajgoel** [comment] 2017-06-20 11:24
I am facing the same issue. 

**For this to work:**
On MAC OS: `dos2unix /usr/local/bin/pdf2txt.py`

But I am not able to do the same for **Ubuntu**. When I run the same command on Ubuntu, and run pdfminer again , it says 

    Traceback (most recent call last):
      File "/usr/local/bin/pdf2txt.py", line 8, in <module>
        import six
    ImportError: No module named six

If anyone has any ideas **please help!**

**Comment by vstoykov** [comment] 2017-08-03 09:20
In the latest version 20170720 the problem still persist if the package is installed from pypi. If you install it directly from github there is no problem, because the file in git is ok.

@goulu on what OS did you prepare the package for PyPi?

The problem is that in Unix like OSes (Linux/BSD/MacOS etc.) in the first line of executable text file there should not be present a `\r` character, because this will mess the shell trying to figure out which interpreter to start in order to execute the file.

As we see in the code everything is ok but there is some problem in the process of creating the package which is uploaded to PyPi.

**Comment by Yepoleb** [comment] 2017-09-06 19:47
> But I am not able to do the same for Ubuntu. When I run the same command on Ubuntu and run pdfminer again , it says
>
> ```
> Traceback (most recent call last):
>   File "/usr/local/bin/pdf2txt.py", line 8, in <module>
>     import six
> ImportError: No module named six
> ```

Use a text editor and change the first line of `/usr/local/bin/pdf2txt.py` from

    #!/usr/bin/env python

to

    #!/usr/bin/env python3

The problem is that you installed the package using pip3 and the script is using Python 2 by default. This should be fixed by switching to setup.py entry points as mentioned earlier.

**Comment by p0ooo0ya** [comment] 2017-09-20 21:56
Both pdf2txt.py and dumppdf.py have this issue. Fixed it by :set ff=unix in vim

**Comment by gedankenstuecke** [comment] 2017-10-20 08:45
Problem still persists as I just installed it using pip on `Ubuntu 16.04.3 LTS` and had to manually fix `pdf2txt.py` to get it to work.

 I ran `sed $'s/\r//' -i $(which pdf2txt.py)` to fix the problem.

**Comment by bittner** [comment] 2017-10-20 09:36
@gedankenstuecke How did you install the module, and [which version](https://pypi.python.org/pypi/pdfminer.six/) is it?

(Run `pip show pdfminer.six`, maybe?)

**Comment by bittner** [comment] 2017-10-20 09:59
Strange. According to the [commit log](https://github.com/pdfminer/pdfminer.six/commits/master) the `\r` issue should have been fixed for that version.

@goulu How do you `sdist upload` new releases? With `python setup.py` or manually? Are you on a Windows machine?

**Comment by tiru1930** [comment] 2018-01-09 07:35
Fixed problem with 

vim `which pdf2txt.py`

:set ff=unix
:wq

**Comment by Thy87** [comment] 2018-02-13 17:10
pip install pdfminer.six is still installing this version:
Version: 20170720
Is there any release of the fix planned ?

**Comment by kbuilds** [comment] 2018-03-07 19:36
To clarify, this was how I patched the installed script:

1. `vim \`which pdf2txt.py\``
2. In Vim: `:set ff=unix`
3. Close the file: `:wq`

**Comment by jekriske-lilly** [comment] 2018-03-23 16:29
This is quite a nasty bug. 
easy fix is `dos2unix pdf2txt.py`
Shouldn't have to if this bug gets fixed.

**Comment by bittner** [comment] 2018-03-23 20:48
Hahaha, this is a nasty bug indeed! I think there are already 2 or 3 commits that tried to fix it, and it keeps coming back! (... or at least it keeps getting reporting.)

Time to write a test for it, maybe?

**Comment by vstoykov** [comment] 2018-03-23 22:39
It's not comming back, because in the code is ok. The problem is only in the package uploaded in PyPi, but @goulu didn't respond for more than an year. We do not know how, on what machine the package was build before it is uploaded to PyPi.

**Comment by AndydeCleyre** [comment] 2018-04-03 15:36
I suggest closing this as a duplicate of #104, where the problem is more specifically identified.

**Comment by jekriske-lilly** [comment] 2018-04-03 15:40
On the contrary #104 is a duplicate of this. What we really want most of all is the version on pypi fixed.

**Comment by AndydeCleyre** [comment] 2018-04-03 15:54
Yes, this one came first. But the other one's title better reflects the issue as you phrased it.

**Comment by vstoykov** [comment] 2018-04-05 09:09
@AndydeCleyre  No mater which issue is described better always the duplicate is the second (third, fourth.. etc.) thing that is coming. Even in this issue at https://github.com/pdfminer/pdfminer.six/issues/27#issuecomment-319915873 I described the problem but there was no response from the author.

We didn't know that @ganeshtata is other person responsible for the package in PyPi in order to ask him for update especially when github doesn't tell us that he has access to the github repo.

But which issue is first/seccond is not important right now. The two issues as linked each other and there is a person with access to PyPi which should be able to fix the problem.

There are two ways I can see that the problem can be fixed.

1. When checkout on windows to configure git to use Linux line endings
2. Change the `setup.py` to not use `scripts`, but instead to use [`entry_points` with `console_scripts`](https://packaging.python.org/tutorials/distributing-packages/#console-scripts). This probably will require a change in location of the tools directory to be a subpackage of `pdfminer` in order to be installed in `site-packages`.

The first option is quick dirty fix.
The second option will need more work but when installing the setuptools will create the appropriate launcher scripts for the current OS with the appropriate shebang for the Python version in which they are installed.

For now because this issue is from a long time I suggest doing 1. and after successfull release to start migrating the code to do 2.

**Comment by SolidOrange** [comment] 2018-10-15 18:21
Still having this issue when trying to download from PyPi. Any update on a fix for this?

**Comment by pietermarsman** [comment] 2019-07-14 14:19
Not sure if this can be closed. The latest release was on the 8th of November, 2018. No comments have been posted here after that. The PR's related to this issue where merged before the release. The same is true for all the other issues that are duplicates of this. So I guess this is fixed and can be closed.

**Comment by pietermarsman** [comment] 2019-07-14 14:23
Checked this to be sure. The checksum for `pdf2text.py` is the same before and after doing `:set ff=unix` in vim.

So this can be closed.

**Closed** 2019-10-13 13:48 UTC
Labels: question
