### ISSUE TITLE
Text is being extracted from image without --all-texts

### ISSUE THREAD

**Issue by joaquimcampos** [pdfminer/pdfminer.six#797] opened 2022-08-22 10:00 UTC
**Bug report**

Text is being extracted from an image (i.e. layout analysis is being performed) without `--all-texts`.
To reproduce:
`pdf2txt.py [pdf_file]` using the following file: [pdfminer_bytes.pdf](https://github.com/pdfminer/pdfminer.six/files/9387033/pdfminer_bytes.pdf).

```
$  pdf2txt.py data/pdfminer_bytes.pdf
1% ΚΑΛΥΤΕΡΟΙ ΚΑΘΕ ΜΕΡΑ

Χειρότεροι κατά 1% καθημερινά επί ένα χρόνο. 

0,99365 = 00,03

Καλύτεροι κατά 1% καθημερινά επί ένα χρόνο. 

1,01365 = 37,78

ΑΠΟΤΕΛΕΣΜΑΤΑ

1% ΒΕΛΤΙΩΣΗ

1% ΕΠΙΔΕΙΝΩΣΗ

ΧΡΟΝΟΣ

ΕΙΚΟΝΑ  1:  Τα  αποτελέσματα  των  μικρών  συνηθειών  πολλα-
πλασιάζονται με το πέρασμα του χρόνου. Για παράδειγμα, αν 
βελτιώνεστε κατά 1% καθημερινά επί ένα χρόνο, στο τέλος του 
χρόνου θα καταλήξετε με ένα αποτέλεσμα 37 φορές καλύτερο.

Οι  συνήθειες  είναι  ο  ανατοκισμός  της  αυτοβελτίωσης  (17). 
Με τον ίδιο τρόπο που τα χρήματα πολλαπλασιάζονται μέσω του 
ανατοκισμού,  πολλαπλασιάζονται  και  οι  επιδράσεις  των  συνη-
θειών σας όσο τις επαναλαμβάνετε τακτικά. Μολονότι η διαφορά 

3434

Ένα τίποτα μπορεί ν’ αλλάξει τα πάντα
```

The text that shouldn't appear is:
```
ΑΠΟΤΕΛΕΣΜΑΤΑ

1% ΒΕΛΤΙΩΣΗ

1% ΕΠΙΔΕΙΝΩΣΗ

ΧΡΟΝΟΣ
```

The problem is that the LTTextContainer is not appearing under the same LTFigure to which the LTImage belongs (even though it is clearly inside the image).
I have manually checked that the LTImage bbox and the LTTextContainer bbox overlap.
I managed to get a fix in place by saving the LTImage bbox and removing all the text from LTTextContainer bbox that overlap horizontally and vertically with it.

**Comment by KunalGehlot** [comment] 2022-08-23 07:17
I was able to reproduce this issue. 

I noticed that in `pdf2txt.py` [line 208](https://github.com/pdfminer/pdfminer.six/blob/ad6587c6970c4efeeb7196bf3e038603c1f77e82/tools/pdf2txt.py#L208) the default value is `la_params.all_texts` which is causing this issue. 

Replacing it with `False` should fix the problem.

**Comment by joaquimcampos** [comment] 2022-08-23 09:55
I believe this can be solved by including all LTTextBox instances whose bbox overlaps with the bbox of an LTFigure instance as children of the latter in the layout tree (which doesn't happen in this example). I am just not sure if this is the expected behaviour.

**Comment by pietermarsman** [comment] 2022-10-15 07:34
The `--all-text` is about the object tree, not where objects are visually displayed. So if an object is not nested inside an `LTFigure` is should be extracted when `--all-text` is used. 

Closing this issue because I assume that this explains it. Let me know if I misunderstood.

**Closed by pietermarsman** 2022-10-15 07:34 UTC
