### ISSUE TITLE
Error on install, UBUNTU 16 LTS

### ISSUE THREAD

**Issue by ppKrauss** [pdfminer/pdfminer.six#60] opened 2017-04-28 01:30 UTC
Errors

1. after `pip install pdfminer.six` ... 100% ... bit fineshed with permission error, 
```
Successfully built pdfminer.six
Installing collected packages: pdfminer.six
Exception:
Traceback (most recent call last):
  File "/home/user/.local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
.....
OSError: [Errno 13] Permission ... '/usr/local/lib/python2.7/dist-packages/pdfminer'
```

2. next repeting with *sudo*, `sudo pip install pdfminer.six` resulted in 
```
The directory '/home/user/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/user/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pdfminer.six
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from pdfminer.six)
Requirement already satisfied: pycrypto in /usr/lib/python2.7/dist-packages (from pdfminer.six)
Installing collected packages: pdfminer.six
Successfully installed pdfminer.six-20170419
```

**but**, no way to call it

`pdf2txt.py myFile.pdf` produced error *"/usr/bin/env: “python\r”: not found"*

**Comment by iameugene** [comment] 2017-04-29 17:33
Did you try sudo's `-H` flag

**Comment by jeeftor** [comment] 2017-07-26 10:44
Got the same error on mac.

**Comment by vstoykov** [comment] 2017-08-02 12:19
Duplicate of #27

**Comment by anshajgoel** [comment] 2017-08-02 16:45
@jeeftor - [`Your solution`](https://github.com/pdfminer/pdfminer.six/issues/27#issuecomment-309724114)

**Comment by pietermarsman** [comment] 2019-10-13 13:55
Closing this as it is a duplicate of #27 

@ppKrauss, feel free to reopen if I am wrong.

**Closed by pietermarsman** 2019-10-13 13:55 UTC
Labels: duplicate
