### ISSUE TITLE
ImportError: cannot import name 'PDFDocument'

### ISSUE THREAD

**Issue by loveJasmine** [pdfminer/pdfminer.six#196] opened 2018-10-22 15:50 UTC
which version support PDFDocument

from pdfminer.pdfparser import PDFParser, PDFDocument

**Comment by ZanonEdoardo** [comment] 2018-11-06 13:09
I use the latest version in pypi and are supported.

**Comment by ganeshtata** [comment] 2018-11-08 17:59
Closing the issue because the latest version doesn't produce the error. Please check with the latest release and reopen the issue if it persists.

**Comment by Mary268** [comment] 2018-11-20 16:19
The problem still remain with the latest git of pdfminer.six from the git:
from pdfminer.pdfparser import PDFDocument
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-8b207b12cfb6> in <module>()
----> 1 from pdfminer.pdfparser import PDFDocument as t

ImportError: cannot import name 'PDFDocument'

Environment:
Successfully built pdfminer.six
Installing collected packages: pdfminer.six
Successfully installed pdfminer.six-20181108

OS: Windows Server 2016

**Comment by ganeshtata** [comment] 2018-11-20 16:31
@Mary268 Does `from pdfminer.pdfdocument import PDFDocument` work?

**Comment by Mary268** [comment] 2018-11-20 16:39
No:
from pdfminer.pdfdocument import PDFDocument
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-15-c01f37196784> in <module>()
----> 1 from pdfminer.pdfdocument import PDFDocument

C:\Program Files\Microsoft\ML Server\PYTHON_SERVER\lib\site-packages\pdfminer\pdfdocument.py in <module>()
     24 from .pdftypes import PDFTypeError
     25 from .pdftypes import PDFStream
---> 26 from .pdftypes import PDFObjectNotFound
     27 from .pdftypes import decipher_all
     28 from .pdftypes import int_value

ImportError: cannot import name 'PDFObjectNotFound'

I have tried pdfminer3k and pdfminer.six, what is the difference between the two?

**Comment by ganeshtata** [comment] 2018-11-20 16:55
`ImportError: cannot import name 'PDFObjectNotFound'`
Strange. The import works for me on my Ubuntu machine, with the latest pdfminer.six, and thus I am having trouble reproducing the issue. 
`I have tried pdfminer3k and pdfminer.six, what is the difference between the two?`
I am sorry, I have no idea about pdfminer3k. This repository is a fork of the original pdfminer, and is being maintained by a few people ( Though the development work is stalled for a while ).

**Comment by pombredanne** [comment] 2018-11-20 18:47
@Mary268 can you provide more details on which Python version you are running and how you installed pdfminer.six? (virtualenv, pip, etc?)

**Comment by Mary268** [comment] 2018-11-20 19:20
pdfminer.six                       20181108
installed by:  pip install git+https://github.com/pdfminer/pdfminer.six.git
python   3.5.2

Actually, it works locally in the VM, but not working (the import error) if published into a Microsoft machine learning service. As u said that it works fine in Ubuntu, I am trying to deploy it again in an Ubuntu Server, and I will update here if any progress.

**Comment by Mary268** [comment] 2018-12-03 15:50
Hi everyone, just an update that the module is not found the problem has been solved in Ubuntu system.So here is some steps I took to solve this problem:

1. **find / -name 'pdfminer'**
find where u have installed the package (my problem is that there are two python runtime thus u'd better find which one you are using)
2. navigate to the directory u have find your 'pdfminer' package, then:
**tree ./**
the tree of your 'pdfminer' package should contain the .py file that u want to use. (e.g. if the pdfducoment.py is not there, how can u import!!! I find mine files is not complete initially, so there is the reason why I can not import!!)
3. if the module u want to import/use is not in the 'pdfminer' package directory, use:
**./pip install git+https://github.com/pdfminer/pdfminer.six.git** (if u can find the pip bin in the python runtime u want to use and navigate to that directory, thus to ensure that u install the package in the python runtime u wanna use)
4. **tree ./** again, here come all the files (including the module u wanna use) from Git!
5. import and use successfully!

Cheers
Mary

**Comment by pombredanne** [comment] 2018-12-04 18:02
Mary:
Using global installations is likely to be the source of your problems.
You should be using a `virtualenv` instead.

**Comment by Mary268** [comment] 2019-02-04 18:56
@pombredanne thank you, and I have just got a chance to reinstall anaconda and creat a new virtual environment, and you are right that the previous problem could also be solved by: 
**conda create -n myenv python=3.6 anaconda**, then installed the package by run:
**source activate myenv**
**conda install -n myenv -c conda-forge pdfminer.six**
But remember to open the Jupter/Spyder/... under the Environment 'myenv' in the Anaconda rather than root(default).

**Comment by Code4SAFrankie** [comment] 2019-03-21 14:08
I did a pip uninstall pdfminer3k and pdfminer.six and then reinstalled both and that fixed it for me.

**Comment by Crescentz** [comment] 2019-03-28 07:25
Problem still exits

**Comment by vm1729** [comment] 2019-04-02 04:08
Friends,
I had the same issue of "cannot import name 'PDFObjectNotFound" when using 
**from pdfminer.pdfdocument import PDFDocument**

**Working Solution**
from pdfminer.pdfparser import PDFParser, PDFDocument

Versions (Pip install):
pdfminer.six                  20181108
pdfminer3k                   1.3.1
Python                          3.6

Sample code:
from pdfminer.pdfparser import PDFParser, PDFDocument
from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
from pdfminer.converter import PDFPageAggregator
from pdfminer.layout import LAParams, LTTextBox, LTTextLine

fp = open('File.pdf', 'rb')
parser = PDFParser(fp)
doc = PDFDocument()
parser.set_document(doc)
doc.set_parser(parser)
doc.initialize('')
rsrcmgr = PDFResourceManager()
laparams = LAParams()
device = PDFPageAggregator(rsrcmgr, laparams=laparams)
interpreter = PDFPageInterpreter(rsrcmgr, device)
# Process each page contained in the document.
for page in doc.get_pages():
    interpreter.process_page(page)
    layout = device.get_result()
    for lt_obj in layout:
        if isinstance(lt_obj, LTTextBox) or isinstance(lt_obj, LTTextLine):
            extracted_text += lt_obj.get_text()
            print(lt_obj.get_text())

fp.close()

**Comment by mdrijwan123** [comment] 2019-06-03 08:47
from pdfminer.pdfparser import PDFParser,PDFPage,PDFDocument # We need to insert PDFPage and and PDFDocument through pdfparser just try if it helps.

**Comment by lycanthropes** [comment] 2019-06-30 01:53
I also met this problem, What can I do ?

**Comment by lunarknight00** [comment] 2019-07-03 07:27
I met the same problem
The PDFDocument is not in the namespace of  `pdfminer.pdfparser`. It is in`pdfminer.pdfdocument`.

That is,

`from pdfminer.pdfdocument import PDFDocument`

Hope it helps!

**Comment by mdrijwan123** [comment] 2019-07-04 15:04
Try to install pdfminer.six only, not pdfminer3k. It solved my problem.

**Comment by KiemVM** [comment] 2019-07-09 02:25
can try to fix:
from pdfminer.pdfparser import PDFParser
from pdfminer.pdfdocument import PDFDocument, PDFNoOutlines
....
doc = PDFDocument(parser, pdf_pwd)

**Comment by pietermarsman** [comment] 2020-05-24 11:00
Solution: only install 1 version of pdfminer in your python environment. Remove all versions of pdfminer (e.g. PDFMiner or pdfminer3k). Then install pdfminer.six with `pip install pdfminer.six`.

**Closed by pietermarsman** 2020-05-24 11:00 UTC
Labels: type: question
