### ISSUE TITLE
PyPI package published with CRLF

### ISSUE THREAD

**Issue by ishitatsuyuki** [pdfminer/pdfminer.six#104] opened 2017-12-06 08:16 UTC
Probably you ran publishing on Windows, and it resulted in broken shebangs.

```
/usr/bin/env: ‘python\r’: No such file or directory
```

**Comment by oct15demo** [comment] 2017-12-12 01:16
If you get this
env: python\r: No such file or directory
In vi open pdf2txt.py and do this
:set ff=unix
As told here:
https://stackoverflow.com/questions/19425857/env-python-r-no-such-file-or-directory

**Comment by ishitatsuyuki** [comment] 2017-12-12 03:49
Sure, there's many way to convert the line format, and even without that running with `python =pdf2txt.py` works because it bypasses shebang. The issue is that the pip package is bad.

**Comment by kerrickstaley** [comment] 2018-01-24 17:22
+1 please fix the package on PIP, it should not use CRLF line endings. The package is unusable on macOS and Linux because of this issue.

**Comment by ganeshtata** [comment] 2018-01-29 11:33
@kerrickstaley Can you please tell me how should I go about doing it? I am an admin of this project, but I am unaware of a lot of specifics.

**Comment by ishitatsuyuki** [comment] 2018-01-30 02:11
@ganeshtata please publish the package again on a non-Windows OS.

**Comment by drunkwcodes** [comment] 2018-03-09 07:12
@ganeshtata 
Or saving those files with line-ending aware editors, such as Notepad++, Sublime Text editor,  Atom etc.

**Comment by pietermarsman** [comment] 2019-07-14 14:25
This is a duplicate of #27. Also, the issue is fixed.

This can be closed.

**Closed** 2019-10-13 13:48 UTC
