### ISSUE TITLE
LAParam all_texts=False not working

### ISSUE THREAD

**Issue by abhilashabhardwaj** [pdfminer/pdfminer.six#649] opened 2021-07-27 13:56 UTC
file1 =  '/Dispatcher_text_in_image.pdf'
    document = open(file4, 'rb')
    rsrcmgr = PDFResourceManager()
    laparams = LAParams(all_texts=False)
    print("AAA laparams::", laparams)
    device = PDFPageAggregator(rsrcmgr, laparams=laparams)
    interpreter = PDFPageInterpreter(rsrcmgr, device)
    for page in PDFPage.get_pages(document):
        interpreter.process_page(page)
        layout = device.get_result()

    for element in layout:
        if isinstance(element, LTTextBoxHorizontal):
            values = element.get_text()
            print (values)

there is an image with text in it (label diagram), but pdfminer is extracting that text as well. How to avoid this?

**Comment by pietermarsman** [comment] 2022-02-12 13:36
Can you share an example PDF that you are using with this code?

**Comment by pietermarsman** [comment] 2022-03-21 22:45
Duplicate of #455

**Closed by pietermarsman** 2022-03-21 22:45 UTC
