### ISSUE TITLE
unable to read from a PDF form

### ISSUE THREAD

**Issue by rahulsarma** [pdfminer/pdfminer.six#168] opened 2018-08-01 05:10 UTC
I have a PDF form. After filling the form, I saved it and used pdf2txt.py. The output did not include the values filled in the form.

**Comment by ganeshtata** [comment] 2018-08-18 16:37
Please post the problematic PDF.

**Comment by pietermarsman** [comment] 2020-01-22 21:30
Closing because not reproducible

**Closed by pietermarsman** 2020-01-22 21:30 UTC
Labels: type: bug
