### ISSUE TITLE
How to know 2 textline is the same sentence

### ISSUE THREAD

**Issue by giangttbkhn** [pdfminer/pdfminer.six#437] opened 2020-06-04 11:16 UTC
I working in domain: CV layout analysis.
I have a question. I using xml format to get position of char,word,sentence to layout analysis, but pdf2text always return 1 line in tag <textline>. I want textlines that same sentences actualy group to tag <textline>.

Same as using **Comand+C** all text of PDF file ---> **Comand V**. Result, I receive actualy sentences in a line.

Can you help me!

**Comment by pietermarsman** [comment] 2020-06-06 13:47
Hi @giangttbkhn,

Thanks for your question but I am not totally sure what you are asking. I think it has something to do with the order of the lines in the output. 

Could you maybe add an example document and show what is going wrong?

**Comment by jstockwin** [comment] 2020-07-09 14:12
@giangttbkhn Just a quick bump as we're trying to sort through all the open issues. Do you have an example PDF so we can replicate this issue?

**Comment by pietermarsman** [comment] 2020-07-18 14:15
Closing this because not reproducible.

**Closed by pietermarsman** 2020-07-18 14:15 UTC
Labels: type: question
