### ISSUE TITLE
pdf2txt.py output getting a lot of (cid:#)

### ISSUE THREAD

**Issue by sean2176** [pdfminer/pdfminer.six#368] opened 2020-02-04 21:28 UTC
I run the pdf2txt.py tool to parse a pdf file and write the output to a text file. I am getting a lot of output like (cid:13), (cid:36), (cid:51) etc.

I wonder what are they? Is any way to remove them?

**Comment by pietermarsman** [comment] 2020-03-08 19:00
Hi @sean2176, thanks for raising the issue. Could you attach the PDF you are using to  your post. And also the script/command that you use. This helps us to debug the issue. 

About cid: this is a font type that is often used to Chinese, Japanese or Korean characters. To convert these characters to text pdfminer.six needs a mapping: from each of the cid drawings to a corresponding unicode value. I expect that the mapping is not specified for the cid codes in your document. But I cannot test that without having access to it.

**Comment by jstockwin** [comment] 2020-07-09 14:23
@sean2176 Just a quick bump as we're trying to sort through all the open issues. Are you able to provide the PDF in question so that we can look into this?

**Comment by matthewmcintire** [comment] 2020-07-10 23:14
I get a (cid:1) on the second line of this pdf. It is a '+' character from a math font.
[0chxb1dv.pdf](https://github.com/pdfminer/pdfminer.six/files/4905865/0chxb1dv.pdf)

**Comment by iforwms** [comment] 2020-07-12 19:09
Same issue here. Here's the `pdffonts` output.

```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
FKSYYD+DFLiSong-W7-WIN-BF            CID Type 0C       Identity-H       yes yes yes    118  0
OWNXIQ+GraphSwift-Bold               Type 1C           MacRoman         yes yes no      17  0
RUJBWP+GraphSwift-Light              Type 1C           MacRoman         yes yes no      18  0
SDJKSN+GraphSwift-LightDCbook        Type 1C           MacRoman         yes yes no      51  0
SBSXZQ+DFSong-XB-80-Win-GB           CID Type 0C       Identity-H       yes yes yes    117  0
OJPEDQ+GraphSwift-LightItalic        Type 1C           MacRoman         yes yes no      19  0
OSLMVM+SimSun                        CID Type 0C       Identity-H       yes yes yes     50  0
```

**Comment by pietermarsman** [comment] 2020-07-18 13:58
> I get a (cid:1) on the second line of this pdf. It is a '+' character from a math font.
> [0chxb1dv.pdf](https://github.com/pdfminer/pdfminer.six/files/4905865/0chxb1dv.pdf)

If I copy the "+" character to somewhere else I get a different character. That means that the math font does not have a proper translation to unicode character. Thus I doubt if pdfminer.six (or any other tool) can recognize that the character is a [+](https://www.compart.com/en/unicode/U+002B) (by inspecting the content of the pdf) (not 100% sure about this)

@sean2176 can you provide the pdf you are having troubles with?

**Comment by Colanim** [comment] 2020-09-09 05:43
I had similar problem in my PDF, I could solve it by normalizing the PDF using `mutools` :

```
sudo apt install mupdf-tools

mutool clean mypdf.pdf out.pdf
```

---

I think it's also possible to normalize it with `ghostscript` :

```
gs -o out.pdf -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress mypdf.pdf
```

**Comment by pietermarsman** [comment] 2020-09-09 07:27
@Colanim that's very interesting! Up until now I assumed that these kind of problems cannot be fixed, because the unicode translation is simply not stored in the pdf. But this assumes that in your case it was stored, and `mutools` was able to recover/repair it. Do you by any chance still have the pdf?

**Comment by Colanim** [comment] 2020-09-09 08:25
I do have the PDF but unfortunately this is confidential, I can't share it...

**Comment by matthewmcintire** [comment] 2020-09-09 23:03
Mine was solved by neither mutool nor gs.

**Comment by pietermarsman** [comment] 2020-10-18 10:39
Closing this because:

- @sean2176 issue is not reproducible because no example pdf
- @matthewmcintire 's pdf has does not have a correct unicode mapping, thus it cannot be fixed
- @Colanim example is not reproducible because pdf cannot be shared

I'm most interested in PDF's where pdfminer.six extracts the wrong character, but some other tool/process extracts the correct character. Please create a new issue if you have an example like this.

**Closed by pietermarsman** 2020-10-18 10:39 UTC
