### ISSUE TITLE
ValueError: unrecognized image mode

### ISSUE THREAD

**Issue by joaquimcampos** [pdfminer/pdfminer.six#795] opened 2022-08-20 12:11 UTC
**Bug report**

This exception is thrown inside when saving an image in `_save_bytes(image)` when `mode='8'`.
It can be triggered with `pdf2txt.py --output-dir [some_dir] [pdf_file]` using the following file: [pdfminer_bytes.pdf](https://github.com/pdfminer/pdfminer.six/files/9387033/pdfminer_bytes.pdf).

The issue has to do with the fact that Pillow (the updated PIL Fork) does not have a mode '8' but has instead a  [mode 'L'](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes).

**Traceback:**

```
/python3.10/site-packages/pdfminer/image.py:126 in       
│ export_image                                                                                    
│                                                                                                 
│   123 │   │   │   name = self._save_bmp(image, width, height, width, image.bits)                
│   124 │   │                                                                                      
│   125 │   │   elif len(filters) == 1 and filters[0][0] in LITERALS_FLATE_DECODE:                
│ ❱ 126 │   │   │   name = self._save_bytes(image)                                                 
│   127 │   │                                                                                      
│   128 │   │   else:                                                                              
│   129 │   │   │   name = self._save_raw(image)                                                   
│                                                                                                  
│ /python3.10/site-packages/pdfminer//python3.10/site-packages/pdfminer/image.py:241 in      
│ _save_bytes                                                                                      
│                                                                                                 
│   238 │   │   │   elif image.bits == 8 and channels == 4:                                       
│   239 │   │   │   │   mode = "CMYK"                                                             
│   240 │   │   │                                                                                 
│ ❱ 241 │   │   │   img = Image.frombytes(mode, image.srcsize, image.stream.get_data(), "raw")    
│   242 │   │   │   img.save(fp)                                                                  
│   243 │   │                                                                                     
│   244 │   │   return name                                                                       
│                                                                                                 
│ /python3.10/site-packages/pdfminer//python3.10/site-packages/PIL/Image.py:2842 in frombytes 
│                                                                                                  
│   2839 │   if decoder_name == "raw" and args == ():                                             
│   2840 │   │   args = mode                                                                      
│   2841 │                                                                                        
│ ❱ 2842 │   im = new(mode, size)                                                                 
│   2843 │   im.frombytes(data, decoder_name, args)                                               
│   2844 │   return im                                                                            
│   2845                                                                                          
│                                                                                                 
│/python3.10/site-packages/pdfminer//python3.10/site-packages/PIL/Image.py:2806 in new       
│                                                                                                 
│   2803 │   │                                                                                    
│   2804 │   │   im.palette = ImagePalette.ImagePalette()                                         
│   2805 │   │   color = im.palette.getcolor(color)                                               
│ ❱ 2806 │   return im._new(core.fill(mode, size, color))                                        
│   2807                                                                                          
│   2808                                                                                          
│   2809 def frombytes(mode, size, data, decoder_name="raw", *args):  

```

Here is a commit that solves the issue:
https://github.com/pdfminer/pdfminer.six/compare/master...joaquimcampos:pdfminer.six:master

**Comment by pietermarsman** [comment] 2022-08-22 06:53
I cannot reproduce this bug. 

```
$ python tools/pdf2txt.py ~/Downloads/pdfminer_bytes.pdf 
1% ΚΑΛΥΤΕΡΟΙ ΚΑΘΕ ΜΕΡΑ

Χειρότεροι κατά 1% καθημερινά επί ένα χρόνο. 

0,99365 = 00,03

Καλύτεροι κατά 1% καθημερινά επί ένα χρόνο. 

1,01365 = 37,78

ΑΠΟΤΕΛΕΣΜΑΤΑ

1% ΒΕΛΤΙΩΣΗ

1% ΕΠΙΔΕΙΝΩΣΗ

ΧΡΟΝΟΣ

ΕΙΚΟΝΑ  1:  Τα  αποτελέσματα  των  μικρών  συνηθειών  πολλα-
πλασιάζονται με το πέρασμα του χρόνου. Για παράδειγμα, αν 
βελτιώνεστε κατά 1% καθημερινά επί ένα χρόνο, στο τέλος του 
χρόνου θα καταλήξετε με ένα αποτέλεσμα 37 φορές καλύτερο.

Οι  συνήθειες  είναι  ο  ανατοκισμός  της  αυτοβελτίωσης  (17). 
Με τον ίδιο τρόπο που τα χρήματα πολλαπλασιάζονται μέσω του 
ανατοκισμού,  πολλαπλασιάζονται  και  οι  επιδράσεις  των  συνη-
θειών σας όσο τις επαναλαμβάνετε τακτικά. Μολονότι η διαφορά 

3434

Ένα τίποτα μπορεί ν’ αλλάξει τα πάντα
```

What version of pdfminer.six are you using? 

Some work on this was done in https://github.com/pdfminer/pdfminer.six/pull/737, which was released in 20220506, maybe you are using an older version?

**Comment by joaquimcampos** [comment] 2022-08-22 09:48
You didn't use the right command, @pietermarsman. You need to add `--output-dir [some_dir]` to extract the images.

**Comment by KunalGehlot** [comment] 2022-08-23 07:08
I confirmed and was able to replicate the issue. 

```bash
(base) kunal@Kunals-MacBook-Pro pdfminer_tests % pdf2txt.py --output-dir . pdfminer_bytes.pdf 
1% ΚΑΛΥΤΕΡΟΙ ΚΑΘΕ ΜΕΡΑ

Χειρότεροι κατά 1% καθημερινά επί ένα χρόνο. 

0,99365 = 00,03

Καλύτεροι κατά 1% καθημερινά επί ένα χρόνο. 

1,01365 = 37,78

ΑΠΟΤΕΛΕΣΜΑΤΑ

1% ΒΕΛΤΙΩΣΗ

1% ΕΠΙΔΕΙΝΩΣΗ

ΧΡΟΝΟΣ

ΕΙΚΟΝΑ  1:  Τα  αποτελέσματα  των  μικρών  συνηθειών  πολλα-
πλασιάζονται με το πέρασμα του χρόνου. Για παράδειγμα, αν 
βελτιώνεστε κατά 1% καθημερινά επί ένα χρόνο, στο τέλος του 
χρόνου θα καταλήξετε με ένα αποτέλεσμα 37 φορές καλύτερο.

Οι  συνήθειες  είναι  ο  ανατοκισμός  της  αυτοβελτίωσης  (17). 
Με τον ίδιο τρόπο που τα χρήματα πολλαπλασιάζονται μέσω του 
ανατοκισμού,  πολλαπλασιάζονται  και  οι  επιδράσεις  των  συνη-
θειών σας όσο τις επαναλαμβάνετε τακτικά. Μολονότι η διαφορά 

3434

Ένα τίποτα μπορεί ν’ αλλάξει τα πάνταTraceback (most recent call last):
  File "/Users/kunal/opt/anaconda3/bin/pdf2txt.py", line 313, in <module>
    sys.exit(main())
  File "/Users/kunal/opt/anaconda3/bin/pdf2txt.py", line 307, in main
    outfp = extract_text(**vars(parsed_args))
  File "/Users/kunal/opt/anaconda3/bin/pdf2txt.py", line 62, in extract_text
    pdfminer.high_level.extract_text_to_fp(fp, **locals())
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/high_level.py", line 121, in extract_text_to_fp
    interpreter.process_page(page)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/pdfinterp.py", line 992, in process_page
    self.device.end_page(page)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/converter.py", line 80, in end_page
    self.receive_layout(self.cur_item)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/converter.py", line 331, in receive_layout
    render(ltpage)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/converter.py", line 320, in render
    render(child)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/converter.py", line 320, in render
    render(child)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/converter.py", line 327, in render
    self.imagewriter.export_image(item)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/image.py", line 125, in export_image
    name = self._save_bytes(image)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/pdfminer/image.py", line 240, in _save_bytes
    img = Image.frombytes(mode, image.srcsize, image.stream.get_data(), "raw")
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/PIL/Image.py", line 2706, in frombytes
    im = new(mode, size)
  File "/Users/kunal/opt/anaconda3/lib/python3.9/site-packages/PIL/Image.py", line 2670, in new
    return im._new(core.fill(mode, size, color))
ValueError: unrecognized image mode
```

The proposed commit does fix the issue, which I ran locally and produced the following image: 
![Im0 1](https://user-images.githubusercontent.com/29948053/186092873-f5922721-1325-4e28-97f9-970a5a48202a.jpg)


I will be creating a PR after running the tests.
Thank you @joaquimcampos

**Comment by pietermarsman** [comment] 2022-10-15 07:31
@joaquimcampos Thanks for pointing that out :+1:

**Closed** 2022-11-05 15:44 UTC
Labels: type: bug, status: accepted
