### ISSUE TITLE
Superscripts causing split of lines

### ISSUE THREAD

**Issue by LCDX** [pdfminer/pdfminer.six#164] opened 2018-07-07 07:09 UTC
Hi, I am converting some journal articles in to text. However, if there is a superscript, the rest of the line will be usually regarded as a new line before the original line.

For example, if I have 'The result of 2^2 is 4.' where 2^2 is square of 2 in superscript form. 
I got '2 is 4\nThe result of 2.

Also, it seems some of the characters are not supported. e.g. The minus sign returns \x00.

Thanks

**Comment by LCDX** [comment] 2018-07-30 11:08
Yes I tried with the file below.

[ac2012653.pdf](https://github.com/pdfminer/pdfminer.six/files/2240860/ac2012653.pdf)

**Comment by brigasnuncamais** [comment] 2018-12-17 08:56
Hi, I got the same issue using [pdfminer.six/tools/pdf2txt.py](https://github.com/pdfminer/pdfminer.six/blob/master/tools/pdf2txt.py) with attached file.
[issue 164.pdf](https://github.com/pdfminer/pdfminer.six/files/2685101/issue.164.pdf)
Analyze : cf parameters in [Command Line Tools in pdfminer](https://www.unixuser.org/~euske/python/pdfminer)
I called pdf2txt.py with different values for these parameters.
The default values are `-M char_margin` = 1.0, `-L line_margin` = 0.3, and `-W word_margin` = 0.2  
For specific cases where next row is too close to previous one, blocks are shuffled. e.g., below block:
<table style="border:2px gray solid"><tr>
<td align=left>N-hydroxylsuccinimide (NHS), and dicyclohexylcarbo-<p>diimde
(DCC) (Aldrich, Milwaukee, WI) were used with-<p>out
further purification. PLGA 75:25 (Medisorb<sup>®</sup>, Mw<p>
120,000) was purchased from Alkermes...</td></tr></table>
<dd>is parsed as (pivot char is <sup>®</sup> where L=0.3 scrambles block order; L=0.1 solves the issue but scrambles some other part of the doc):
<table style="border:2px gray solid"><tr>
<td align=left>N-hydroxylsuccinimide (NHS), and dicyclohexylcarbo-<p>
diimde (DCC) (Aldrich, Milwaukee, WI) were used with-<p>
out
, Mw<p>
120,000) was purchased from Alkermes...<p>
further puriﬁcation. PLGA 75:25 (Medisorb</td></tr></table>
<p><dt><em>also -F boxes_flow</em>
<dd>specifies how much a horizontal and vertical position of a text block matters
when determining text parsing order. The value should be within the range of 
-1.0 (only horizontal position matters) to +1.0 (only vertical position matters).
The default value is 0.5.
<p><p><dt><em>&rarr; Issue</em>
<dd>In below case, upper right text block is parsed before lower left text block ! Only setting boxes_flow = -1.0 parses lower left block before upper right one, but with wrong sorting of other blocks in the document. Cause may be presence of an image block on upper left part of this page.
[issue.164_boxes_flow.pdf.pdf](https://github.com/pdfminer/pdfminer.six/files/2685126/issue.164_boxes_flow.pdf.pdf)

**Comment by atraining** [comment] 2020-02-28 11:41
Hi, just to update the issue: You should check if the commit https://github.com/pdfminer/pdfminer.six/commit/fff3ac2ba6121660e0f7178150d665215d8586d7 solves your issue. Many issues, i.e. linebreaks for superscripts were solved for our PDFs. Great work - @pietermarsman !

**Comment by pietermarsman** [comment] 2020-03-14 15:09
Looking at the example PDF, I think the problem is caused by subsequent subscript and superscript. These have no vertical overlap and are therefore not considered to be on the same line. 

I lack ideas on how we can solve this in a robust way.

**Comment by pietermarsman** [comment] 2020-05-17 16:19
I get good results with: 

```
pdf2txt.py Downloads/ac2012653.pdf -p 1 --line-margin 0.1
```

The problem is that a subscript followed by a superscript prevents the merging of two parts of the sentence adjacent to the sub super. Lines above and below do get merged and that is why the order is scrambles. If you set line-margin to a low value (e.g. `--line-margin 0.1`) almost none of the lines get merged into a box. This allows the boxes-flow algorithm to order the lines a more appropriate way, than the line-margin algorithm is able to. 

Output without line-margin:

```
Effect of the Charge State (z = (cid:1)1, 0, +1) on the Nuclear Magnetic
Resonance of Monodisperse Au25[S(CH2)2Ph]18
Alfonso Venzo,||,‡ Sabrina Antonello,|| Jos(cid:1)e A. Gasc(cid:1)on,§ Ivan Guryanov,|| Richard D. Leapman,^
Neranjan V. Perera,§ Alioscka Sousa,^ Martina Zamuner,|| Alessandro Zanella,|| and Flavio Maran||,*

z Clusters

)
```

Output with a low line-margin:

```
Effect of the Charge State (z = (cid:1)1, 0, +1) on the Nuclear Magnetic
Resonance of Monodisperse Au25[S(CH2)2Ph]18

z Clusters

Alfonso Venzo,||,‡ Sabrina Antonello,|| Jos(cid:1)e A. Gasc(cid:1)on,§ Ivan Guryanov,|| Richard D. Leapman,^
Neranjan V. Perera,§ Alioscka Sousa,^ Martina Zamuner,|| Alessandro Zanella,|| and Flavio Maran||,*

Department of Chemistry, University of Padova, via Marzolo 1, 35131 Padova, Italy
```

The "z Clusters" phrase is still on its own line which is not ideal. But it is in the correct order, after " Au25[S(CH2)2Ph]18".

**Closed** 2020-05-17 16:19 UTC
Labels: component: layout, type: bug
